OS-4358 should ensure required nic tags are available before running tests

diff --git a/src/vm/runtest b/src/vm/runtest
--- a/src/vm/runtest
+++ b/src/vm/runtest
@@ -56,6 +56,15 @@ for img in $(comm -1 -3 <(eval ${installed_images}) <(eval ${want_images})); do
     imgadm import "${img}"
 done
 
+# Ensure nic tags needed by tests exist
+
+for tag in admin external; do
+    if ! /usr/bin/nictagadm exists ${tag} >/dev/null 2>&1; then
+        echo "Missing NIC tag: ${tag}, please add w/ nictagadm and try again" >&2
+        exit 2
+    fi
+done
+
 set +o errexit
 set -o pipefail
 /usr/node/bin/node --abort_on_uncaught_exception \
