SmartOS 20110926 update

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -177,8 +177,43 @@ if [ ! -f on-closed-bins-nd.i386.tar.bz2 ]; then
   tar xvpf on-closed-bins-nd.i386.tar.bz2
 fi
 
+
+#
+# Use environment variables to determine if we should be building debug or not,
+# etc.
+#
+# ILLUMOS_ENABLE_LINT
+# ILLUMOS_ENABLE_DEBUG=yes|exclusive
+#
+# ENABLE_LINT implies ENABLE_DEBUG=yes
+#
+	
+NIGHTLY_OPTIONS_BASE="-CimNnt"
+NIGHTLY_EXTRA=""
+
+NIGHTLY_DEBUG=0
+ENABLE_LINT=0
+if [[ "$ILLUMOS_ENABLE_LINT" != "" ]]; then
+	ENABLE_LINT=1
+	ENABLE_DEBUG=1
+fi
+
+if [[ "$ILLUMOS_ENABLE_DEBUG" == "yes" ]]; then
+	ENABLE_DEBUG=1
+elif [[ "$ILLUMOS_ENABLE_DEBUG" == "exclusive" ]]; then
+	ENABLE_DEBUG=2
+elif [[ "$ILLUMOS_ENABLE_DEBUG" != "" ]]; then
+	echo "Unknown value for ILLUMOS_ENABLE_DEBUG: $ILLUMOS_ENABLE_DEBUG"
+	echo "Aborting configure."
+	exit 1
+fi
+
+[[ $ENABLE_LINT -eq 1 ]] && NIGHTLY_EXTRA="l"
+[[ $ENABLE_DEBUG -eq 1 ]] && NIGHTLY_EXTRA=$NIGHTLY_EXTRA"D"
+[[ $ENABLE_DEBUG -eq 2 ]] && NIGHTLY_EXTRA=$NIGHTLY_EXTRA"DF"
+
 cat <<EOF> illumos.sh
-NIGHTLY_OPTIONS="-CimNnt"; export NIGHTLY_OPTIONS
+NIGHTLY_OPTIONS="$NIGHTLY_OPTIONS_BASE$NIGHTLY_EXTRA"; export NIGHTLY_OPTIONS
 GATE="${RELEASE_VER}"; export GATE
 CODEMGR_WS="${ROOT}/projects/illumos"; export CODEMGR_WS
 maxjobs() {
@@ -229,14 +264,7 @@ function update_branch
     cd ${target_dir}
     current=$(git branch | grep "^*" | cut -d' ' -f2)
     if [[ "${current}" != "${target}" ]]; then
-        if [[ -n $(git branch | grep " ${target}$") ]]; then
-            # have branch already, checkout
-            git checkout ${target}
-        else
-            # don't have, add to tracking and checkout
-            git branch --track ${target} origin/${target}
-            git checkout ${target}
-        fi
+		  git checkout ${target}
     fi
     cd ${oldwd}
 
diff --git a/overlay/lib/svc/method/net-physical b/overlay/lib/svc/method/net-physical
--- a/overlay/lib/svc/method/net-physical
+++ b/overlay/lib/svc/method/net-physical
@@ -45,14 +45,212 @@ LD_LIBRARY_PATH=/lib; export LD_LIBRARY_PATH
 
 smf_netstrategy
 
+function log_if_state
+{
+    echo "== debug start: $1 =="
+    if ! dladm show-phys; then
+        echo "WARNING: 'dladm show-phys' failed"
+    fi
+    # NOTE: DO NOT do a 'dladm show-linkprop' when using the bnx driver,
+    # as it puts it into an unusable state!
+    if ! /sbin/ifconfig -a; then
+        echo "WARNING: 'ifconfig -a' failed"
+    fi
+    echo "== debug end: $1 =="
+}
+
+# Creates, plumbs and brings up a vnic with the specified parameters
+function vnic_up
+{
+    typeset link="$1"
+    typeset iface="$2"
+    typeset ip="$3"
+    typeset netmask="$4"
+    typeset vlan_id="$5"
+    typeset mac_addr="$6"
+    typeset dhcp_primary="$7"
+    typeset details="link='${link}', iface='${iface}', ip='${ip}', netmask='${netmask}, vlan_id='${vlan_id}'"
+    typeset vlan_opt=
+    typeset mac_addr_opt=
+
+    if [[ -z ${link} ]] || [[ -z ${iface} ]] || [[ -z ${ip} ]] || [[ -z ${netmask} ]]; then
+        echo "WARNING: not bringing up nic (insufficient configuration): $details"
+        return
+    fi
+
+    eval "vnic_already_up=\${vnic_${iface}_up}"
+    if [[ -n "${vnic_already_up}" ]]; then
+        echo "vnic already up: $details"
+        return
+    fi
+    echo "Bringing up nic: $details"
+
+    if [[ -n ${vlan_id} ]] && [[ ${vlan_id} != 0 ]]; then
+        vlan_opt="-v ${vlan_id}"
+    fi
+
+    if [[ -n ${mac_addr} ]]; then
+        mac_addr_opt="-m ${mac_addr}"
+    fi
+
+    dladm create-vnic -l ${link} ${vlan_opt} ${mac_addr_opt} ${iface}
+    ifconfig ${iface} plumb
+
+    if [[ ${ip} == "dhcp" ]]; then
+        # We ignore errors here because the most common one is that DHCP
+        # is already running.
+
+        if [[ -n ${dhcp_primary} ]]; then
+            ifconfig ${iface} dhcp primary || /bin/true
+        else
+            ifconfig ${iface} dhcp || /bin/true
+        fi
+    else
+        ifconfig ${iface} inet ${ip} netmask ${netmask} up
+    fi
+    eval "vnic_${iface}_up=true"
+}
+
 if smf_is_globalzone; then
 
     dladm init-phys
-    for iface in `dladm show-phys -p -o link`; do
-	ifconfig ${iface} plumb
-	ifconfig ${iface} dhcp
-    done
 
+    # The next command is for logging purposes only
+    log_if_state before
+
+    # Load sysinfo variables with SYSINFO_ prefix
+    load_sdc_sysinfo
+    # Load config variables with CONFIG_ prefix, and sets the headnode variable
+    load_sdc_config
+    # Load boot params with BOOT_ prefix
+    load_sdc_bootparams
+
+    # Setup admin NIC
+    if [[ -n ${SYSINFO_NIC_admin} ]]; then
+        ifconfig ${SYSINFO_NIC_admin} plumb
+        if [[ ${headnode} == "true" ]]; then
+            if [[ -n ${CONFIG_admin_ip} ]] && [[ -n ${CONFIG_admin_netmask} ]];
+            then
+                ifconfig ${SYSINFO_NIC_admin} inet ${CONFIG_admin_ip} \
+                    netmask ${CONFIG_admin_netmask} up
+                ADMIN_NIC_UP=true
+
+                # also setup resolv.conf if we can
+                if [[ -n ${CONFIG_dns_domain} ]] && [[ -n ${CONFIG_dns_resolvers} ]]; then
+                    echo "search ${CONFIG_dns_domain}" > /etc/resolv.conf
+                    for serv in $(echo "${CONFIG_dns_resolvers}" | sed -e "s/,/ /g"); do
+                        echo "nameserver ${serv}" >> /etc/resolv.conf
+                    done
+                fi
+            else
+                echo "ERROR: headnode but no admin_{ip,netmask} in config, not bringing up admin network."
+                # Set a flag, but try to plumb the other interfaces anyway
+                ADMIN_NIC_MISCONFIGURED=true
+            fi
+         elif [[ -n $(/usr/bin/bootparams | grep "^smartos") ]]; then
+            if [[ -n ${CONFIG_admin_ip} ]] && [[ -n ${CONFIG_admin_netmask} ]]; then
+                ifconfig ${SYSINFO_NIC_admin} inet ${CONFIG_admin_ip} \
+                    netmask ${CONFIG_admin_netmask} up
+                ADMIN_NIC_UP=true
+
+                # also setup resolv.conf if we can
+                if [[ -n ${CONFIG_dns_domain} ]] && [[ -n ${CONFIG_dns_resolvers} ]]; then
+                    echo "search ${CONFIG_dns_domain}" > /etc/resolv.conf
+                    for serv in $(echo "${CONFIG_dns_resolvers}" | sed -e "s/,/ /g"); do
+                        echo "nameserver ${serv}" >> /etc/resolv.conf
+                    done
+                fi
+            else
+                ifconfig ${SYSINFO_NIC_admin} dhcp || /bin/true
+                ADMIN_NIC_UP=true
+            fi
+
+        else
+            # We ignore errors here because the most common one is that DHCP is
+            # already running.
+            ifconfig ${SYSINFO_NIC_admin} dhcp || /bin/true
+            ADMIN_NIC_UP=true
+        fi
+        # If on VMWare, create a bridge which allows traffic to flow correctly to the host-only network
+        if [[ "${ADMIN_NIC_UP}" == "true" ]] && [[ ${SYSINFO_Product} == "VMware Virtual Platform" ]]; then
+            dladm create-bridge -l ${SYSINFO_NIC_admin} vmwarebr
+        fi
+    else
+        echo "ERROR: admin NIC not found, unable to bring up admin network."
+        exit ${SMF_EXIT_ERR_CONFIG}
+    fi
+
+    # Setup external NIC
+    if [[ -n ${SYSINFO_NIC_external} ]] && [[ -n "${CONFIG_external_ip}" ]]; then
+        vnic_up "${SYSINFO_NIC_external}" "external0" "${CONFIG_external_ip}" \
+            "${CONFIG_external_netmask}" "${CONFIG_external_vlan_id}" "" "primary"
+    fi
+
+    # Set up the GZ to NAT for Coal
+    if [[ -n ${SYSINFO_NIC_external} ]] && [[ -n "${CONFIG_external_ip}" ]] &&
+        [[ "${CONFIG_coal}" == "true" ]]; then
+
+        # Convert the admin IP and netmask to CIDR notation
+        CIDR=$(ip_netmask_to_cidr ${CONFIG_admin_ip} ${CONFIG_admin_netmask})
+
+        # Allow zones to reach the internet using the global zone as a router
+        cat >> /etc/ipf/ipnat.conf <<IPNAT
+map external0 ${CIDR} -> 0.0.0.0/32
+map external0 ${CIDR} -> 0.0.0.0/32 portmap tcp/udp auto
+IPNAT
+    fi
+
+    # Use headnode_default_gateway if set, otherwise fall back to admin_gateway
+    # if that's set.
+    if [[ -n "${CONFIG_headnode_default_gateway}" ]]; then
+        echo "${CONFIG_headnode_default_gateway}" > /etc/defaultrouter
+    elif [[ -n ${CONFIG_admin_gateway} ]]; then
+        echo "${CONFIG_admin_gateway}" > /etc/defaultrouter
+    fi
+
+    # Setup extra nics, if specified in the config file
+    nic_tags="${SYSINFO_Nic_Tags}"
+    if [[ -n "${nic_tags}" ]]; then
+        tags=(${nic_tags//,/ })
+
+        bootparam_ip_keys=$(sdc_bootparams_keys | grep -- "-ip$" || true)
+        config_ip_keys=$(sdc_config_keys | grep "_ip$" || true)
+        for tag in "${tags[@]}"; do
+
+            eval "link=\${SYSINFO_NIC_${tag}}"
+            if [[ -z "${link}" ]]; then
+                echo "WARNING: No link found with tag '${tag}'"
+                continue
+            fi
+
+            for key in ${config_ip_keys}; do
+                if [[ ${key} == ${tag}[0-9]_ip ]] || [[ ${key} == ${tag}[0-9][0-9]_ip ]]; then
+                    iface=${key//_ip/}
+                    #echo "   iface=$iface"
+                    eval "ip=\${CONFIG_${iface}_ip}"
+                    eval "netmask=\${CONFIG_${iface}_netmask}"
+                    eval "vlan=\${CONFIG_${iface}_vlan_id}"
+                    eval "macaddr=\${CONFIG_${iface}_mac}"
+
+                    echo vnic_up "${link}" "${iface}" "${ip}" "${netmask}" "${vlan}" "${macaddr}"
+                    vnic_up "${link}" "${iface}" "${ip}" "${netmask}" "${vlan}" "${macaddr}"
+                fi
+            done
+
+            for key in ${bootparam_ip_keys}; do
+                if [[ ${key} == ${tag}[0-9]-ip ]] || [[ ${key} == ${tag}[0-9][0-9]-ip ]]; then
+                    iface=${key//-ip/}
+                    eval "ip=\${BOOT_${iface}_ip}"
+                    eval "netmask=\${BOOT_${iface}_netmask}"
+                    eval "vlan=\${BOOT_${iface}_vlan_id}"
+                    eval "macaddr=\${BOOT_${iface}_mac}"
+                    echo vnic_up "${link}" "${iface}" "${ip}" "${netmask}" "${vlan}" "${macaddr}"
+                    vnic_up "${link}" "${iface}" "${ip}" "${netmask}" "${vlan}" "${macaddr}"
+                fi
+            done
+
+        done
+    fi
 else
     # Non-global zones
     for iface in `dladm show-vnic -p -o link`; do
@@ -65,22 +263,16 @@ else
     done
 fi
 
-# The next commands are for logging purposes only
-echo "== debug start: after =="
-if ! dladm show-phys; then
-    echo "WARNING: 'dladm show-phys' failed"
-fi
-# NOTE: DO NOT do a 'dladm show-linkprop' when using the bnx driver,
-# as it puts it into an unusable state!
-# TODO: do a show-linkprop if not using bnx
-if ! /sbin/ifconfig -a; then
-    echo "WARNING: 'ifconfig -a' failed"
-fi
-echo "== debug end: after =="
+log_if_state after
 
 # Since we hopefully made networking changes here, update the sysinfo cache
 if smf_is_globalzone; then
     /usr/bin/sysinfo -u
+fi
+
+# If the admin nic was missing config options, exit with a config error
+if [[ -n "${ADMIN_NIC_MISCONFIGURED}" ]]; then
+    exit ${SMF_EXIT_ERR_CONFIG}
 fi
 
 # Any non-loopback IPv4 interfaces with usable addresses up?
