OS-8164 smartos-live projects infrastructure should add refspecs for pull requests

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12,7 +12,7 @@
 #
 
 #
-# Copyright 2019 Joyent, Inc.
+# Copyright 2020 Joyent, Inc.
 #
 shopt -s xpg_echo
 unalias -a
@@ -109,9 +109,24 @@ function checkout_project
 			local branch_desc=$(echo $branch | sed -e 's/\//_/g')
 
 			# We assume the remote is named 'origin'.
-			git -C ${dir} fetch origin ${branch}:${branch_desc} || \
-				fatal "unable to fetch ${branch} from origin"
+			git -C ${dir} fetch origin ${branch}:${branch_desc}
 
+			# If the above fails, see if the project appears to be a GitHub
+			# PR-xxx branch name, and if so, add the relevant refspec for
+			# pull requests
+			if [[ $? -eq 0 ]]; then
+				PR_BRANCH=$(echo "${branch}" | sed -e 's/^PR-[0-9]+$//g')
+				if [[ -z "${PR_BRANCH}" ]]; then
+					echo "Branch appears to be from a PR, adding github refspec"
+					PR_NUMBER=$(echo ${PR_BRANCH} | awk -F- '{print $2}')
+					git -C ${dir} config --add remote.origin.fetch \
+					    +refs/pull/${PR_NUMBER}/head:refs/remotes/origin/${PR_BRANCH}
+					git -C ${dir} fetch || \
+					    fatal "unable to fetch using PR refspec"
+				else
+					fatal "unable to fetch ${branch} from origin"
+				fi
+			fi
 			git -C ${dir} checkout ${branch_desc} || \
 				fatal "unable to checkout ${branch_desc}"
 		fi
