move upgrade to be before installations

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -210,6 +210,11 @@ function install_pkgin
 	$conf_priv pkgin -f update || fatal "failed to update pkgsrc repository"
 
 	#
+	# Make sure we've upgraded all of our installed packages.
+	#
+	$conf_priv pkgin -y upgrade || fatal "failed installed-package upgrades"
+
+	#
 	# Remove legacy packages replaced by the smartos-build-tools package.
 	#
 	for pkg in astmsgtools dmake rpcgen sgstools; do
@@ -224,11 +229,6 @@ function install_pkgin
 		    "failed to install $pkg"
 		fi
 	done
-
-	#
-	# Make sure we've upgraded all of our installed packages.
-	#
-	$conf_priv pkgin -y upgrade || fatal "failed installed-package upgrades"
 }
 
 function install_ips
