smartos-live#2 Fixed identation, spaces should be tabs smartos-live#51 No symlink for libusb.so to libusb.so.1 for -lusb smartos-live#86 'make clean' fails if Node.js hasn't been built smartos-live#91 make world fails on trying to include zlib.h OS-1301 smartos-live subprojects should be told about the proto area OS-1302 smartos-live should offer a way to bootstrap illumos-extra OS-1303 smartos-live src_addon can die OS-1304 smartos-live src build should not use node-waf OS-1305 illumos-extra should not put libuuid.a into the proto area, ever OS-1306 non-bootstrappable runtime dependencies should be isolated OS-1310 smartos-live build doesn't fail even if kvm-cmd completely bombs out OS-1312 smartos-live makefiles must fit in 80 columns OS-1317 GZ crle configuration pollution

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -141,14 +141,28 @@ if [ ! -f "projects/illumos/usr/src/tools/env/illumos.sh" ]; then
   fi
 fi
 
-if [[ -n ${ILLUMOS_EXTRA_TARBALL_URL} && -z ${NO_EXTRA_TARBALL} ]]; then
-	EXTRA_TARBALL=$(curl -k ${ILLUMOS_EXTRA_TARBALL_URL} | grep href | tail -n1 | cut -d '"' -f2)
-	curl -k -O ${ILLUMOS_EXTRA_TARBALL_URL}/${EXTRA_TARBALL}
-	if [[ $? != 0 ]]; then
-		EXTRA_TARBALL=""
-	fi
+#
+# The adjunct tarball contains headers and libraries against which runtime
+# dependencies will be encoded into our delivered objects.  It should not
+# exist but is essential until illumos becomes self-contained.
+#
+if [[ -z "${ILLUMOS_ADJUNCT_TARBALL_URL}" ]]; then
+	echo "FATAL: No ILLUMOS_ADJUNCT_TARBALL_URL defined in configure.*"
+	exit 1
 fi
-if [[ ! -f "projects/illumos-extra/Makefile" && -z $EXTRA_TARBALL ]]; then
+ADJUNCT_TARBALL="$(curl -k ${ILLUMOS_ADJUNCT_TARBALL_URL} | \
+    grep href | tail -n1 | cut -d '"' -f2)"
+if [[ -z "${ADJUNCT_TARBALL}" ]]; then
+	echo "FATAL: Unable to list adjunct from ILLUMOS_ADJUNCT_TARBALL_URL"
+	exit 1
+fi
+curl -k -O ${ILLUMOS_ADJUNCT_TARBALL_URL}/${ADJUNCT_TARBALL}
+if [[ $? != 0 ]]; then
+	echo "FATAL: Unable to get adjuncts from ILLUMOS_ADJUNCT_TARBALL_URL"
+	exit 1
+fi
+
+if [[ ! -f "projects/illumos-extra/Makefile" ]]; then
   echo " +--> Getting illumos-extra source tree..."
   if [ -z "${GET_ILLUMOS_EXTRA}" ]; then
     echo "FATAL: No GET_ILLUMOS_EXTRA defined in configure.*, can't get illumos-extra!"
@@ -260,6 +274,8 @@ ON_CLOSED_BINS="\$CODEMGR_WS/closed";            export ON_CLOSED_BINS
 ON_CRYPTO_BINS="\$CODEMGR_WS/on-crypto.\$MACH.tar.bz2"; export ON_CRYPTO_BINS
 REF_PROTO_LIST=\$PARENT_WS/usr/src/proto_list_\${MACH}; export REF_PROTO_LIST
 ROOT="${ROOT}/proto";  export ROOT
+ADJUNCT_PROTO="${ROOT}/proto.strap";	export ADJUNCT_PROTO
+NATIVE_ADJUNCT="/opt/local";		export NATIVE_ADJUNCT
 SRC="\$CODEMGR_WS/usr/src";              export SRC
 VERSION="\$GATE";                        export VERSION
 PARENT_ROOT="${ROOT}/proto"; export PARENT_ROOT
