OS-2164 reprovision needs to run some of the commands from brand's install script.

diff --git a/overlay/generic/usr/lib/brand/joyent-minimal/jinstall b/overlay/generic/usr/lib/brand/joyent-minimal/jinstall
--- a/overlay/generic/usr/lib/brand/joyent-minimal/jinstall
+++ b/overlay/generic/usr/lib/brand/joyent-minimal/jinstall
@@ -30,14 +30,19 @@ export PATH
 . /usr/lib/brand/shared/common.ksh
 . /usr/lib/brand/joyent-minimal/common.ksh
 
+REPROVISIONING=""
 ZONENAME=""
 ZONEPATH=""
 # Default to 10GB diskset quota
 ZQUOTA=10
 
-while getopts "R:t:U:q:z:" opt
+while getopts "rR:t:U:q:z:" opt
 do
 	case "$opt" in
+		r)
+			set -x
+			REPROVISIONING="true"
+			;;
 		R)	ZONEPATH="$OPTARG";;
 		t)	TMPLZONE="$OPTARG";;
 			# UUID is only used in the postinstall script
@@ -50,12 +55,19 @@ do
 done
 shift OPTIND-1
 
-if [[ -n $(zonecfg -z "${ZONENAME}" info attr name=transition \
+#
+# IMPORTANT: all actions below need to consider reprovision. If the action
+# modifies files in the zoneroot itself, it should be run on reprovision
+# any other changes to the zone or dataset should not be done on reprovision.
+#
+
+if [[ -z ${REPROVISIONING} \
+    && -n $(zonecfg -z "${ZONENAME}" info attr name=transition \
     | grep "value: receiving:") ]]; then
 
-    # Here we're doing an install for a received zone, the dataset should have
-    # already been created.
-    exit $ZONE_SUBPROC_OK
+	# Here we're doing an install for a received zone, the dataset should have
+	# already been created.
+	exit $ZONE_SUBPROC_OK
 fi
 
 if [[ -z $ZONEPATH || -z $ZONENAME ]]; then
@@ -63,38 +75,44 @@ if [[ -z $ZONEPATH || -z $ZONENAME ]]; then
 	exit $ZONE_SUBPROC_USAGE
 fi
 
-# The install requires a template zone.
-if [[ -z $TMPLZONE ]]; then
-	print -u2 "Brand error: a zone template is required"
-	exit $ZONE_SUBPROC_USAGE
-fi
+if [[ -z ${REPROVISIONING} ]]; then
+	# The install requires a template zone.
+	if [[ -z $TMPLZONE ]]; then
+		print -u2 "Brand error: a zone template is required"
+		exit $ZONE_SUBPROC_USAGE
+	fi
 
-# The dataset quota must be a number.
-case $ZQUOTA in *[!0-9]*)
-	print -u2 "Brand error: The quota $ZQUOTA is not a number"
-	exit $ZONE_SUBPROC_USAGE;;
-esac
+	# The dataset quota must be a number.
+	case $ZQUOTA in *[!0-9]*)
+		print -u2 "Brand error: The quota $ZQUOTA is not a number"
+		exit $ZONE_SUBPROC_USAGE;;
+	esac
+fi
 
 ZROOT=$ZONEPATH/root
 
-# Get the dataset of the parent directory of the zonepath.
-dname=${ZONEPATH%/*}
-bname=${ZONEPATH##*/}
-PDS_NAME=`mount | nawk -v p=$dname '{if ($1 == p) print $3}'`
-[ -z "$PDS_NAME" ] && \
-    print -u2 "Brand error: missing parent ZFS dataset for $dname"
+if [[ -z ${REPROVISIONING} ]]; then
+	# Get the dataset of the parent directory of the zonepath.
+	dname=${ZONEPATH%/*}
+	bname=${ZONEPATH##*/}
+	PDS_NAME=`mount | nawk -v p=$dname '{if ($1 == p) print $3}'`
+	[ -z "$PDS_NAME" ] && \
+	    print -u2 "Brand error: missing parent ZFS dataset for $dname"
 
-# We expect that zoneadm was invoked with '-x nodataset', so it won't have
-# created the dataset.
+	# We expect that zoneadm was invoked with '-x nodataset', so it won't have
+	# created the dataset.
 
-QUOTA_ARG=
-if [[ ${ZQUOTA} != "0" ]]; then
-    QUOTA_ARG="-o quota=${ZQUOTA}g"
+	QUOTA_ARG=
+	if [[ ${ZQUOTA} != "0" ]]; then
+		QUOTA_ARG="-o quota=${ZQUOTA}g"
+	fi
+
+	zfs snapshot $PDS_NAME/${TMPLZONE}@${bname}
+	zfs clone -F ${QUOTA_ARG} $PDS_NAME/${TMPLZONE}@${bname} \
+	    $PDS_NAME/$bname || fatal "failed to clone zone dataset"
 fi
 
-zfs snapshot $PDS_NAME/${TMPLZONE}@${bname}
-zfs clone -F ${QUOTA_ARG} $PDS_NAME/${TMPLZONE}@${bname} \
-    $PDS_NAME/$bname || fatal "failed to clone zone dataset"
+# The rest should be run when REPROVISIONING is set as well.
 
 # Make sure zoneinit is setup to use -o xtrace, this handles old datasets where
 # is not yet enabled by default.
