OS-1736 Allow creating / modifying firewall rules in the GZ

diff --git a/overlay/generic/usr/lib/brand/joyent-minimal/statechange b/overlay/generic/usr/lib/brand/joyent-minimal/statechange
--- a/overlay/generic/usr/lib/brand/joyent-minimal/statechange
+++ b/overlay/generic/usr/lib/brand/joyent-minimal/statechange
@@ -377,6 +377,46 @@ setup_net()
 }
 
 #
+# Log a message, then exit
+#
+log_and_exit()
+{
+	echo "$1"
+	logger -p daemon.err "zone $ZONENAME $1"
+	exit 1
+}
+
+#
+# Set up the firewall for the zone.
+#
+setup_fw()
+{
+	ipf_conf=$ZONEPATH/config/ipf.conf
+	if [ -e $ipf_conf ]; then
+		echo "starting firewall ($ipf_conf)"
+		/usr/sbin/ipf -E $ZONENAME
+		if (( $? != 0 )); then
+			log_and_exit "error enabling ipfilter"
+		fi
+
+		/usr/sbin/ipf -Fa $ZONENAME
+		if (( $? != 0 )); then
+			log_and_exit "error flushing ipfilter"
+		fi
+
+		/usr/sbin/ipf -f $ipf_conf $ZONENAME
+		if (( $? != 0 )); then
+			log_and_exit "error loading ipfilter config"
+		fi
+
+		/usr/sbin/ipf -y $ZONENAME
+		if (( $? != 0 )); then
+			log_and_exit "error syncing ipfilter interfaces"
+		fi
+	fi
+}
+
+#
 # We're readying the zone.  Make sure the per-zone writable
 # directories exist so that we can lofs mount them.  We do this here,
 # instead of in the install script, since this list has evolved and
@@ -601,6 +641,7 @@ load_sdc_config
 if [[ "$subcommand" == "post" && $cmd == 0 ]]; then
 	setup_snapshots
 	setup_net
+	setup_fw
 fi
 
 # We can't set a rctl until we have a process in the zone to grab
