Versioning for USB key Introduce /lib/sdc/usb-key.sh and use it

diff --git a/overlay/generic/lib/svc/method/fs-joyent b/overlay/generic/lib/svc/method/fs-joyent
--- a/overlay/generic/lib/svc/method/fs-joyent
+++ b/overlay/generic/lib/svc/method/fs-joyent
@@ -24,6 +24,7 @@ fatal()
 
 . /lib/svc/share/smf_include.sh
 . /lib/svc/share/fs_include.sh
+. /lib/sdc/usb-key.sh
 
 # first of all, if we aren't the global zone this doesn't make any sense to run
 
@@ -218,11 +219,8 @@ if [ -d /var/upgrade_in_progress ]; then
     exit $SMF_EXIT_ERR_FATAL
 fi
 
-USBMOUNTPOINT=/mnt/`svcprop -p "joyentfs/usb_mountpoint" ${SMF_FMRI}`
 COPYINPOINT=`svcprop -p "joyentfs/usb_copy_path" ${SMF_FMRI}`
 DEBUG=`svcprop -p "joyentfs/debug" ${SMF_FMRI}`
-
-mount_usb_msg=""
 
 if [[ -d /mnt ]]; then
     chown root:root /mnt
@@ -281,62 +279,10 @@ function make_usb_copy_if_possible
     return 0
 }
 
-mkdir -p ${USBMOUNTPOINT}
-
-if [[ -f "${USBMOUNTPOINT}/.joyliveusb" ]]; then
-    mount_usb_msg="already mounted"
-    make_usb_copy_if_possible
-    exit $?
+USBMOUNTPOINT=$(mount_usb_key "")
+if [[ $? -ne 0 ]]; then
+    fatal "couldn't mount USB key"
 fi
 
-# First thing to do is to mount the USB key / VMWare disk
-readonly alldisks=$(/usr/bin/disklist -a)
-#
-# Older MBR/GRUB-based USB keys will have a single primary partition containing
-# the root filesystem.  Newer, GPT/Loader-based USB keys will have multiple
-# slices with the root partition at slice 2.  We don't currently have a good
-# way of knowing in advance which style of USB key we're dealing with, so we
-# search for both possibilities.
-#
-readonly partitions=("p0:1" "p1" "s2")
-
-for disk in ${alldisks}; do
-    for part in ${partitions[@]}; do
-        devpath="/dev/dsk/${disk}${part}"
-        if [[ `/usr/sbin/fstyp $devpath` == 'pcfs' ]]; then
-            /usr/sbin/mount -F pcfs -o foldcase,noatime $devpath \
-              ${USBMOUNTPOINT};
-            if [[ $? == "0" ]]; then
-                if [[ ! -f ${USBMOUNTPOINT}/.joyliveusb ]]; then
-                    if [[ ${DEBUG} == "true" ]]; then
-                        mount_usb_msg="${mount_usb_msg}\n[debug] didn't find 
-		          ${USBMOUNTPOINT}/.joyliveusb on pcfs $devpath"
-                    fi
-                    /usr/sbin/umount ${USBMOUNTPOINT};
-                else
-                    if [[ ${DEBUG} == "true" ]]; then
-                        mount_usb_msg="${mount_usb_msg}\n[debug] found 
-		          ${USBMOUNTPOINT}/.joyliveusb on pcfs $devpath"
-                    fi
-		    found_key=1
-                    break;
-                fi
-            elif [[ ${DEBUG} == "true" ]]; then
-                mount_usb_msg="${mount_usb_msg}\n[debug] mount failed for 
-	          pcfs $devpath"
-            fi
-        elif [[ ${DEBUG} == "true" ]]; then
-            mount_usb_msg="${mount_usb_msg}\n[debug] $devpath is not pcfs"
-        fi
-    done
-    [[ $found_key == 1 ]] && break
-done
-
-if [[ -f "${USBMOUNTPOINT}/.joyliveusb" ]]; then
-    mount_usb_msg="success"
-    make_usb_copy_if_possible
-    exit $?
-fi
-
-mount_usb_msg="${mount_usb_msg}\n[FATAL] mount_usb(): could not find USB Key"
-exit 1;
+make_usb_copy_if_possible
+exit $?
