OS-7260 SmartOS should support booting with loader OS-7271 proto.boot should include loader instead of grub OS-7309 build tools should support loader-based boot images OS-7364 fs_joyent.sh test needs quotes Portions contributed by: Rob Johnston <rob.johnston@joyent.com> Reviewed by: Robert Mustacchi <rm@joyent.com> Reviewed by: Jerry Jelinek <jerry.jelinek@joyent.com> Approved by: Robert Mustacchi <rm@joyent.com>

diff --git a/overlay/generic/lib/svc/method/fs-joyent b/overlay/generic/lib/svc/method/fs-joyent
--- a/overlay/generic/lib/svc/method/fs-joyent
+++ b/overlay/generic/lib/svc/method/fs-joyent
@@ -24,6 +24,7 @@ fatal()
 
 . /lib/svc/share/smf_include.sh
 . /lib/svc/share/fs_include.sh
+. /lib/sdc/usb-key.sh
 
 # first of all, if we aren't the global zone this doesn't make any sense to run
 
@@ -107,7 +108,7 @@ if [ $? -ne 0 ]; then
     # A machine is reset to its original unsetup state (i.e. a 'factory reset')
     # when the smartdc:factoryreset ZFS user property is set on the var dataset.
     reset=$(zfs get -H -o value smartdc:factoryreset ${SYS_ZPOOL}/var)
-    if [ ${reset} == "yes" ]; then
+    if [ "${reset}" == "yes" ]; then
         destroy_zpools
     fi
 
@@ -218,11 +219,8 @@ if [ -d /var/upgrade_in_progress ]; then
     exit $SMF_EXIT_ERR_FATAL
 fi
 
-USBMOUNTPOINT=/mnt/`svcprop -p "joyentfs/usb_mountpoint" ${SMF_FMRI}`
 COPYINPOINT=`svcprop -p "joyentfs/usb_copy_path" ${SMF_FMRI}`
 DEBUG=`svcprop -p "joyentfs/debug" ${SMF_FMRI}`
-
-mount_usb_msg=""
 
 if [[ -d /mnt ]]; then
     chown root:root /mnt
@@ -260,7 +258,7 @@ function make_usb_copy_if_possible
     mkdir ${COPYINPOINT}
     mount_zfs ${USBDATASET} ${COPYINPOINT}
 
-    $(cd ${USBMOUNTPOINT}; rsync -av --log-file=/dev/console --exclude private --exclude os * ${COPYINPOINT})
+    (cd ${USBMOUNTPOINT}; rsync -av --log-file=/dev/console --exclude private --exclude os * ${COPYINPOINT})
     if [[ -d ${USBMOUNTPOINT}/os ]]; then
         (cd ${USBMOUNTPOINT}/os ; \
             for dir in $(ls -d *); do
@@ -281,72 +279,10 @@ function make_usb_copy_if_possible
     return 0
 }
 
-mkdir -p ${USBMOUNTPOINT}
-
-if [[ -f "${USBMOUNTPOINT}/.joyliveusb" ]]; then
-    mount_usb_msg="already mounted"
-    make_usb_copy_if_possible
-    exit $?
+USBMOUNTPOINT=$(mount_usb_key "")
+if [[ $? -ne 0 ]]; then
+    fatal "couldn't mount USB key"
 fi
 
-# First thing to do is to mount the USB key / VMWare disk
-USBKEYS=`/usr/bin/disklist -a`
-for key in ${USBKEYS}; do
-    if [[ `/usr/sbin/fstyp /dev/dsk/${key}p0:1` == 'pcfs' ]]; then
-        /usr/sbin/mount -F pcfs -o foldcase,noatime /dev/dsk/${key}p0:1 \
-            ${USBMOUNTPOINT};
-        if [[ $? == "0" ]]; then
-            if [[ ! -f ${USBMOUNTPOINT}/.joyliveusb ]]; then
-                if [[ ${DEBUG} == "true" ]]; then
-                    mount_usb_msg="${mount_usb_msg}\n[debug] didn't find ${USBMOUNTPOINT}/.joyliveusb on pcfs /dev/dsk/${key}p0:1"
-                fi
-                /usr/sbin/umount ${USBMOUNTPOINT};
-            else
-                if [[ ${DEBUG} == "true" ]]; then
-                    mount_usb_msg="${mount_usb_msg}\n[debug] found ${USBMOUNTPOINT}/.joyliveusb on pcfs /dev/dsk/${key}p0:1"
-                fi
-                break;
-            fi
-        elif [[ ${DEBUG} == "true" ]]; then
-            mount_usb_msg="${mount_usb_msg}\n[debug] mount failed for pcfs /dev/dsk/${key}p0:1"
-        fi
-    elif [[ ${DEBUG} == "true" ]]; then
-        mount_usb_msg="${mount_usb_msg}\n[debug] /dev/dsk/${key}p0:1 is not pcfs"
-    fi
-done
-
-if [[ ! -f "${USBMOUNTPOINT}/.joyliveusb" ]]; then
-    # we're probably VMWare, so we're looking at a non-USB disk.
-    for disk in `/usr/bin/disklist -a`; do
-        if [[ `/usr/sbin/fstyp /dev/dsk/${disk}p1` == 'pcfs' ]]; then
-            /usr/sbin/mount -F pcfs -o foldcase,noatime /dev/dsk/${disk}p1 \
-                ${USBMOUNTPOINT};
-            if [[ $? == "0" ]]; then
-                if [[ ! -f ${USBMOUNTPOINT}/.joyliveusb ]]; then
-                    if [[ ${DEBUG} == "true" ]]; then
-                        mount_usb_msg="${mount_usb_msg}\n[debug] didn't find ${USBMOUNTPOINT}/.joyliveusb on pcfs /dev/dsk/${disk}p1"
-                    fi
-                    /usr/sbin/umount ${USBMOUNTPOINT};
-                else
-                    if [[ ${DEBUG} == "true" ]]; then
-                        mount_usb_msg="${mount_usb_msg}\n[debug] found ${USBMOUNTPOINT}/.joyliveusb on pcfs /dev/dsk/${disk}p1"
-                    fi
-                    break;
-                fi
-            elif [[ ${DEBUG} == "true" ]]; then
-                mount_usb_msg="${mount_usb_msg}\n[debug] unable to mount /dev/dsk/${disk}p1"
-            fi
-        elif [[ ${DEBUG} == "true" ]]; then
-            mount_usb_msg="${mount_usb_msg}\n[debug] /dev/dsk/${disk}p1 is not pcfs"
-        fi
-    done
-fi
-
-if [[ -f "${USBMOUNTPOINT}/.joyliveusb" ]]; then
-    mount_usb_msg="success"
-    make_usb_copy_if_possible
-    exit $?
-fi
-
-mount_usb_msg="${mount_usb_msg}\n[FATAL] mount_usb(): could not find USB Key"
-exit 1;
+make_usb_copy_if_possible
+exit $?
