OS-2515 run operator-script on OS VMs when set.

diff --git a/overlay/generic/lib/svc/method/mdata-execute b/overlay/generic/lib/svc/method/mdata-execute
--- a/overlay/generic/lib/svc/method/mdata-execute
+++ b/overlay/generic/lib/svc/method/mdata-execute
@@ -35,6 +35,15 @@ if [ -f /var/svc/provisioning ]; then
     mv /var/svc/provision{ing,_success}
 fi
 
+if [[ -x /var/svc/mdata-operator-script ]]; then
+    /var/svc/mdata-operator-script
+    operator_script_exit=$?
+    if [[ ${operator_script_exit} -gt 0 ]]; then
+        echo "WARNING: operator-script failed: exited ${operator_script_exit}" \
+            >&2
+    fi
+fi
+
 user_script_exit=${SMF_EXIT_OK}
 if [ -x /var/svc/mdata-user-script ]; then
     /var/svc/mdata-user-script
diff --git a/overlay/generic/lib/svc/method/mdata-fetch b/overlay/generic/lib/svc/method/mdata-fetch
--- a/overlay/generic/lib/svc/method/mdata-fetch
+++ b/overlay/generic/lib/svc/method/mdata-fetch
@@ -95,6 +95,24 @@ case $? in
     ;;
 esac
 
+echo "Retrieving metadata operator-script..."
+/usr/sbin/mdata-get sdc:operator-script >/var/svc/mdata-operator-script.new
+case $? in
+  0)
+    echo "Metadata operator-script successfuly retrieved."
+    mv /var/svc/mdata-operator-script{.new,}
+    chmod +x /var/svc/mdata-operator-script
+    ;;
+  1)
+    echo "Metadata operator-script not defined."
+    rm -f /var/svc/mdata-operator-script{,.new}
+    ;;
+  *)
+    echo "Metadata couldn't be retrieved."
+    exit ${SMF_EXIT_ERR_FATAL}
+    ;;
+esac
+
 echo "Retrieving tmpfs value..."
 tmpfs=$(/usr/sbin/mdata-get sdc:tmpfs)
 if [[ $? == 0 && -n ${tmpfs} && -f /etc/vfstab ]]; then
