OS-7075 platform needs to be rackaware Reviewed by: Dan McDonald <danmcd@joyent.com> Reviewed by: Jason King <jason.king@joyent.com> Approved by: Michael Zeller <mike.zeller@joyent.com>

diff --git a/overlay/generic/lib/svc/method/net-physical b/overlay/generic/lib/svc/method/net-physical
--- a/overlay/generic/lib/svc/method/net-physical
+++ b/overlay/generic/lib/svc/method/net-physical
@@ -64,6 +64,7 @@ function log_if_state
 {
     set -o xtrace
     echo "== debug start: $1 =="
+    nictagadm list
     if ! /usr/sbin/dladm show-phys; then
         echo "WARNING: 'dladm show-phys' failed"
     fi
@@ -422,19 +423,19 @@ function setup_mtu
             exit $SMF_EXIT_ERR_FATAL
         fi
 
-	#
-	# Check the current MTU of the device. To help out devices which
-	# don't support the setting of the MTU (here's looking at you
-	# bnx), if the MTU is identical to its default, don't do
-	# anything and save the poor folks stuck with bnx some grief.
-	#
-	curmtu=$(/usr/sbin/dladm show-linkprop -c -o value -p mtu ${link})
-	[[ $? -eq 0 ]] && [[ "$curmtu" -eq "${mtus[$mac]}" ]] && continue
+        #
+        # Check the current MTU of the device. To help out devices which
+        # don't support the setting of the MTU (here's looking at you
+        # bnx), if the MTU is identical to its default, don't do
+        # anything and save the poor folks stuck with bnx some grief.
+        #
+        curmtu=$(/usr/sbin/dladm show-linkprop -c -o value -p mtu ${link})
+        [[ $? -eq 0 ]] && [[ "$curmtu" -eq "${mtus[$mac]}" ]] && continue
 
-        if ! /usr/sbin/dladm set-linkprop -p mtu=${mtus[$mac]} ${link}; then
-            echo "Failed to set mtu to ${mtus[$mac]} for link ${link}"
-            exit $SMF_EXIT_ERR_FATAL
-        fi
+            if ! /usr/sbin/dladm set-linkprop -p mtu=${mtus[$mac]} ${link}; then
+                echo "Failed to set mtu to ${mtus[$mac]} for link ${link}"
+                exit $SMF_EXIT_ERR_FATAL
+            fi
     done
 }
 
@@ -498,6 +499,7 @@ if smf_is_globalzone; then
     setup_mtu
 
     # Setup admin NIC
+    ADMIN_NIC_TAG=${CONFIG_admin_tag:-"admin"}
 
     # If there is no NIC with the admin tag, and the config has
     # admin_nic_autoselect=true, designate the first NIC reported
@@ -505,14 +507,14 @@ if smf_is_globalzone; then
     # the NICs are known to change beneath us.
     if [[ "${BOOT_smartos}" == "true" ]] && \
         [[ "${CONFIG_admin_nic_autoselect}" == "true" ]] && \
-        ! nictagadm exists admin ; then
+        ! nictagadm exists $ADMIN_NIC_TAG ; then
         autoselected_admin_nic=$(dladm show-phys -m -p -o address | head -n1)
         if [[ -z ${autoselected_admin_nic} ]] ; then
             echo "ERROR: no NICs found, unable to autoselect admin NIC."
             exit ${SMF_EXIT_ERR_CONFIG}
         fi
 
-        nictagadm add admin "${autoselected_admin_nic}"
+        nictagadm add $ADMIN_NIC_TAG "${autoselected_admin_nic}"
         if [[ $? -ne 0 ]] ; then
             echo "ERROR: unable to add admin tag to NIC ${autoselected_admin_nic}"
             exit ${SMF_EXIT_ERR_FATAL}
@@ -524,6 +526,19 @@ if smf_is_globalzone; then
         fi
 
         nictagadm list
+    elif [[ -v CONFIG_admin_tag ]]; then
+        #
+        # This handles the case when the 'admin_tag' property is set to
+        # override the default admin nic tag.
+        #
+        eval SYSINFO_NIC_admin='$'SYSINFO_NIC_${CONFIG_admin_tag}
+
+        eval CONFIG_admin_ip='$'CONFIG_${CONFIG_admin_tag}_ip
+        eval CONFIG_admin_ip6='$'CONFIG_${CONFIG_admin_tag}_ip6
+        eval CONFIG_admin_netmask='$'CONFIG_${CONFIG_admin_tag}_netmask
+        eval CONFIG_admin_mtu='$'CONFIG_${CONFIG_admin_tag}_mtu
+        eval CONFIG_admin_gateway='$'CONFIG_${CONFIG_admin_tag}_gateway
+        eval CONFIG_admin_gateway6='$'CONFIG_${CONFIG_admin_tag}_gateway6
     fi
 
     if [[ -z "${SYSINFO_NIC_admin}" ]]; then
