use publish/bits-upload machinery for both ctftools and strap cache

diff --git a/tools/build_strap b/tools/build_strap
--- a/tools/build_strap
+++ b/tools/build_strap
@@ -9,7 +9,7 @@
 # source.  A copy of the CDDL is also available via the Internet at
 # http://www.illumos.org/license/CDDL.
 #
-# Copyright 2018 Joyent, Inc.
+# Copyright 2020 Joyent, Inc.
 #
 
 #
@@ -27,13 +27,14 @@
 # we'll fall back to doing a full strap build of illumos-extra.  This is also
 # true if the user specified non-default compilers.
 #
+# The -l and -t options are used when building and uploading a new cache.
+#
 
-usage="$0 [-l | -a adjunct.tar [-f] [-j maxjobs] [-c | -d protodir]]"
+usage="$0 [-l | -a adjunct.tar [-f] [-j maxjobs] [-t tarfile | -d protodir]]"
 wsroot=$(cd $(dirname $0)/../; pwd)
 pkgin_file="/opt/local/etc/pkgin/repositories.conf"
-manta_host="https://us-east.manta.joyent.com"
-manta_dir="/Joyent_Dev/public/SmartOS/build-cache/proto.strap/"
-manta_base="$manta_host/$manta_dir"
+manta_dir="/Joyent_Dev/public/SmartOS/build-cache/master"
+manta_base="https://us-east.manta.joyent.com/$manta_dir"
 cache_base="/opt/SmartOS/build-cache/"
 srcdir="$wsroot/projects/illumos-extra"
 adjunct=""
@@ -41,7 +42,7 @@ protodir=""
 max_jobs="128"
 force_build="no"
 report_loc="no"
-create_cache="no"
+tarfile=""
 
 function fatal
 {
@@ -102,8 +103,8 @@ function download
 	local pkgsrc_branch=$1
 	local srcdirsha=$2
 	local cache_dir="$cache_base/$pkgsrc_branch/$srcdirsha"
-	local outfile="/var/tmp/$srcdirsha.proto.strap.tgz.$$"
-	local url="$manta_base/$pkgsrc_branch/$srcdirsha/proto.strap.tgz"
+	local outfile="/var/tmp/$srcdirsha.proto.strap.tar.gz.$$"
+	local url="$manta_base/$pkgsrc_branch/$srcdirsha/proto.strap.tar.gz"
 	local tmpdir="$cache_dir.$$"
 
 	pfexec mkdir -p "$tmpdir" || fatal "failed to make $cache_dir"
@@ -147,27 +148,26 @@ function download
 function create_cache
 {
 	local cache_dir="$1"
+	local tarfile="$2"
 
-	if [[ "$force_build" = "no" ]]; then
-		if [[ -d "$cache_dir" ]]; then
-			echo "$cache_dir exists; not building"
-			return
-		fi
+	if [[ "$force_build" = "yes" || ! -d "$cache_dir" ]]; then
+		pfexec mkdir -p "$cache_dir" || \
+		    fatal "couldn't mkdir $cache_dir"
+		pfexec chown $(id -u) "$cache_dir" || \
+		    fatal "couldn't chown $cache_dir"
+
+		protodir="$cache_dir"
+
+		build_strap
 	fi
 
-	pfexec mkdir -p "$cache_dir" || fatal "couldn't mkdir $cache_dir"
-	pfexec chown $(id -u) "$cache_dir" || fatal "couldn't chown $cache_dir"
+	pfexec gtar -C "$cache_dir" -czf "$tarfile" . ||
+	    fatal "failed to create $tarfile"
 
-	protodir="$cache_dir"
+	pfexec chown $(id -u) "$tarfile" || \
+	    fatal "couldn't chown $tarfile"
 
-	build_strap
-
-	mkdir -p $wsroot/output || fatal "couldn't mkdir $wsroot/output"
-
-	gtar -C "$cache_dir" -czf $wsroot/output/proto.strap.tgz . ||
-	    fatal "failed to create tarball"
-
-	echo "Created $wsroot/output/proto.strap.tgz"
+	echo "Created $tarfile."
 }
 
 #
@@ -184,8 +184,8 @@ function populate_strap
 		fatal "found weird non-directory $cache_dir"
 	fi
 
-	if [[ "$create_cache" = "yes" ]]; then
-		create_cache $cache_dir
+	if [[ -n "$tarfile" ]]; then
+		create_cache $cache_dir $tarfile
 		return
 	fi
 
@@ -219,12 +219,10 @@ function populate_strap
 export PATH=/usr/bin:/usr/sbin:/sbin:/opt/local/bin:/opt/local/sbin
 set -o pipefail
 
-while getopts "a:cd:fhlj:" arg; do
+while getopts "a:d:fhlj:t:" arg; do
 	case $arg in
 	a)
 		adjunct=$OPTARG ;;
-	c)
-		create_cache="yes" ;;
 	d)
 		protodir=$OPTARG ;;
 	f)
@@ -236,6 +234,8 @@ while getopts "a:cd:fhlj:" arg; do
 		max_jobs=$OPTARG ;;
 	l)
 		report_loc="yes" ;;
+	t)
+		tarfile=$OPTARG ;;
 	?)
 		echo "$usage" >&2
 		exit 1 ;;
@@ -243,7 +243,7 @@ while getopts "a:cd:fhlj:" arg; do
 done
 
 if [[ "$report_loc" = "yes" ]]; then
-	echo $manta_dir/$(identify_pkgsrc_branch)/$(identify_srcsha)/proto.strap.tgz
+	echo $(identify_pkgsrc_branch)/$(identify_srcsha)
 	exit 0
 fi
 
@@ -251,8 +251,8 @@ fi
 [[ -d "$srcdir" ]] || fatal "cannot find illumos-extra in $srcdir"
 [[ -d "$srcdir/.git" ]] || fatal "$srcdir is not a git repo"
 
-if [[ "$create_cache" = "yes" ]]; then
-	[[ -z "$protodir" ]] || fatal "can't specify -u and -d"
+if [[ -n "$tarfile" ]]; then
+	[[ -z "$protodir" ]] || fatal "can't specify -n and -d"
 else
 	[[ -n "$protodir" ]] || fatal "missing -d argument"
 fi
