Added new C builder tool which is more than 100x faster than the old method.  Also do other major cleanup on liveimg build process.

diff --git a/tools/build_live b/tools/build_live
--- a/tools/build_live
+++ b/tools/build_live
@@ -25,11 +25,10 @@
 # Use is subject to license terms.
 
 ROOT=`pwd`
-PROTO=${ROOT}/proto
 MAN_DIR=${ROOT}/projects/opensolaris-man
-ALT_ROOT=${ROOT}/overlay
-OUT_DIR=${ROOT}/output
 CUSTOMIZE_SCRIPT=${ROOT}/tools/customize
+SMF_IMPORTER=${ROOT}/tools/smf_import
+BUILDER=${ROOT}/tools/builder/builder
 SCANNER=${ROOT}/tools/scanner
 BUILDSTAMP=`TZ=UTC date "+%Y%m%dT%H%M%SZ"`; export BUILDSTAMP 
 LOGFILE="${ROOT}/log/build_live.${BUILDSTAMP}.log"
@@ -37,13 +36,17 @@ ERROR=0
 PLATFORM=i86pc
 ISA=i386
 ARCH64=amd64
-MANIFEST=
 SIZE=700000
 BOOT_ARCHIVE_64=platform-${BUILDSTAMP}/$PLATFORM/$ARCH64/boot_archive
 OUT_KERNEL_64=platform-${BUILDSTAMP}/$PLATFORM/kernel/$ARCH64/unix
 KERNEL_64=platform/$PLATFORM/kernel/$ARCH64/unix
 PREFIX=platform-${BUILDSTAMP}
 compress=no
+
+if [ "$(id -u)" != "0" ]; then
+  echo "You must have euid 0 to run this tool."
+  exit 1
+fi
 
 # Send a copy of stdout and stderr to LOGFILE
 exec > >(tee ${LOGFILE}) 2>&1
@@ -54,63 +57,33 @@ export GZIP_CMD=/usr/bin/gzip
 usage() {
     echo "This tool is for building a live boot_archive amd64."
     echo ""
-    echo "Usage: ${0##*/}: [-P <proto>] [-A <altroot>] [-o <outdir>] <manifest>"
+    echo "Usage: ${0##*/}: <manifest> <outdir> <dir> [<dir> <dir> ...]"
     exit 1
 }
 
-#
-# Parse options
-#
-while [ "$1" != "" ]
-do
-    case $1 in
-        -R|-r) 
-            shift
-            ROOT="$1"
-        ;;
-        -a|-A)
-            shift
-            ALT_ROOT="$1"
-        ;;
-        -o)
-            shift
-            OUT_DIR="$1"
-        ;;
-        -?|-h)
-            usage
-        ;;
-        *)
-            if [ -z "${MANIFEST}" ]; then
-                MANIFEST=$1
-            else
-                # We already had manifest on cmdline, this is a usage problem
-                usage
-            fi
-        ;;
-    esac
-    shift
-done
+MANIFEST=$1
+shift
+OUT_DIR=$1
+shift
+IN_DIRS=$*
 
 # We need the manifest file
 if [ -z "${MANIFEST}" ] || [ ! -f "${MANIFEST}" ]; then
-    echo "FATAL: manifest file required"
+    echo "FATAL: <manifest> file required"
     usage
-fi
-
-# We need the PROTO dir
-if [ -z "${PROTO}" ] || [ ! -d "${PROTO}" ]; then
-    echo "FATAL: root ${PROTO} required (Specify with -P <proto>)"
-    usage
-fi
-
-# If we have an ALT_ROOT specified, it must exist
-if [ ! -z "${ALT_ROOT}" ]; then 
-    if [ ! -d "${ALT_ROOT}" ]; then
-        echo "FATAL: ${ALT_ROOT} does not exist."
-        usage
-    fi
 else
-    echo "WARNING: no -A <altroot> specified, files will only come from ${PROTO}"
+    # translate to abs path
+    MANIFEST=$(cd $(dirname ../manifest) && pwd)
+fi
+
+if [ -z "${OUT_DIR}" ]; then
+    echo "FATAL: <outdir> required."
+    usage
+fi
+
+if [ -z "${IN_DIRS}" ]; then
+    echo "FATAL: at least one <dir> required."
+    usage
 fi
 
 if [ ! -d "${OUT_DIR}" ]; then
@@ -121,99 +94,22 @@ if [ ! -d "${OUT_DIR}" ]; then
     fi
 fi
 
+num=0
 echo "=== Options/ ==="
-echo "PROTO ..... ${PROTO}"
-echo "ALT_ROOT .. ${ALT_ROOT}"
+echo "MANIFEST .. ${MANIFEST}"
 echo "OUTPUT .... ${OUT_DIR}"
-echo "MANIFEST . ${MANIFEST}"
+for dir in ${IN_DIRS}; do
+  num=$((${num} + 1))
+  echo "DIR[$(printf '%02d' ${num})] ... ${dir}"
+done
 echo "=== /Options ==="
 
 
-function copy_files
-{
-    while read line
-    do
-        # Squeeze multiple spaces/tabs into one space
-        line=`echo "${line}" | sed -e "s/	/ /" | tr -s ' '`
-    
-        # Remove leading/trailing spaces
-        line=`echo "${line}" | sed -e "s/ +$//" | sed -e "s/^ +//"`
-    
-        if [ ! -z "${line}" ] && [ `echo "${line}" | cut -c1` != "#" ]; then
-            echo "${line}" | { read e_type e_target e_mode e_owner e_group e_guard
-                result="OK"
-                case ${e_type} in
-                    d)
-                        pfexec install -s -d -m ${e_mode} -u ${e_owner} -g ${e_group} ${rdmnt}/${e_target}
-                        pfexec [ -d "${rdmnt}/${e_target}" ] || result="*FAILED*"
-                        echo "${result} - DIR: ${e_target}"
-                    ;;
-                    f)
-                        where=""
-
-                        # First preference is to copy from ALT/overlay dir
-                        pfexec cp -p ${ALT_ROOT}/${e_target} ${rdmnt}/${e_target} 2>/dev/null && where="A"
-                            
-                        # If it wasn't copied in from ALT/overlay, copy from proto area
-                        if pfexec [ ! -f "${rdmnt}/${e_target}" ]; then
-                            pfexec cp -p ${PROTO}/${e_target} ${rdmnt}/${e_target} 2>/dev/null && where="P"
-                        fi
-
-                        # copy man pages from MAN_DIR if they've not been copied from proto / overlay dir
-                        if pfexec [ ! -f "${rdmnt}/${e_target}" ] && echo "${e_target}" | grep "^usr\/share\/man\/" >/dev/null 2>&1; then
-                            man_file=`echo "${e_target}" | sed -e "s/^usr\/share\/man\///"`
-                            pfexec cp -p ${MAN_DIR}/${man_file} ${rdmnt}/${e_target} 2>/dev/null && where="M"
-                        fi
-
-                        # Fallback to build system's version if still doesn't exist.
-                        if pfexec [ ! -f "${rdmnt}/${e_target}" ]; then
-                            pfexec cp -p /${e_target} ${rdmnt}/${e_target} 2>/dev/null && where="S"
-                        fi
-
-                        if pfexec [ -f "${rdmnt}/${e_target}" ]; then
-                            pfexec chmod ${e_mode} ${rdmnt}/${e_target}
-                            pfexec chown ${e_owner}:${e_group} ${rdmnt}/${e_target}
-                            result="OK[${where}]"
-                        else
-                            result="*FAILED*"
-                        fi
-                        echo "${result} - FILE: ${e_target}"
-                    ;;
-                    s)
-                        target=`echo ${e_target} | cut -d'=' -f2`
-                        source=`echo ${e_target} | cut -d'=' -f1`
-                        (cd ${rdmnt} ; \
-                            pfexec ln -s ${target} ${source} ; \
-                        )
-                        echo "${result} - SYMLINK: ${target} -> ${source}"
-                    ;;
-                    h)
-                        target=`echo ${e_target} | cut -d'=' -f2`
-                        source=`echo ${e_target} | cut -d'=' -f1`
-                        (cd ${rdmnt} ; \
-                            pfexec ln ${target} ${source} ; \
-                        )
-                        echo "${result} - LINK: ${target} -> ${source}"
-                    ;;
-                    *)
-                        echo "FATAL: UNKNOWN TYPE: ${line}"
-                        exit 1
-                    ;;
-                esac
-            } 
-        else
-            # Ignore comments and blank lines
-            /bin/true
-            #echo "IGNORE: ${line}"
-        fi
-    done <"${MANIFEST}"
-}
-
 function cleanup
 {
-    pfexec umount -f "${rdmnt}" 2>/dev/null
-    pfexec lofiadm -d "${rdfile}" 2>/dev/null
-    [ -n "${rddir}" ] && pfexec rm -fr "${rddir}" 2> /dev/null
+    umount -f "${rdmnt}" 2>/dev/null
+    lofiadm -d "${rdfile}" 2>/dev/null
+    [ -n "${rddir}" ] && rm -fr "${rddir}" 2> /dev/null
 }
 
 function create_ufs
@@ -221,25 +117,26 @@ function create_ufs
     archive=$1
     lofidev=$2
 
-    pfexec newfs ${lofidev} < /dev/null 2> /dev/null
-    pfexec mkdir "${rdmnt}"
-    pfexec mount -F ufs -o nologging ${lofidev} "${rdmnt}"
+    newfs ${lofidev} < /dev/null 2> /dev/null
+    mkdir "${rdmnt}"
+    mount -F ufs -o nologging ${lofidev} "${rdmnt}"
 
     # do the actual copy
-    copy_files
-    ${CUSTOMIZE_SCRIPT} ${rdmnt} ${ALT_ROOT}
+    ${BUILDER} ${MANIFEST} ${rdmnt} ${IN_DIRS}
+    ${CUSTOMIZE_SCRIPT} ${rdmnt} ${OVERLAY}
+    ${SMF_IMPORT} ${rdmnt}
 
     echo "Writing manifest.."
-    INCLUDE_MD5SUM=1 pfexec ${SCANNER} ${rdmnt} . | pfexec tee ${rdmnt}/var/log/manifest >/dev/null
-    pfexec cp ${rdmnt}/var/log/manifest ${archive}.manifest
+    INCLUDE_MD5SUM=1 ${SCANNER} ${rdmnt} . | tee ${rdmnt}/var/log/manifest >/dev/null
+    cp ${rdmnt}/var/log/manifest ${archive}.manifest
 
-    pfexec umount -f "$rdmnt"
-    pfexec rmdir "$rdmnt"
-    pfexec gzip "$rdfile" && pfexec mv "${rdfile}.gz" "${archive}-new"
+    umount -f "$rdmnt"
+    rmdir "$rdmnt"
+    gzip "$rdfile" && mv "${rdfile}.gz" "${archive}-new"
 
     if [ $? -ne 0 ] ; then
-        pfexec rm -f "${archive}-new"
-        pfexec rm -f "${archive}.manifest"
+        rm -f "${archive}-new"
+        rm -f "${archive}.manifest"
     fi
 }
 
@@ -249,7 +146,7 @@ function create_archive
     lofidev=$2
 
     echo "creating ${archive} (${lofidev})"
-    pfexec mkdir -p `dirname ${archive}`
+    mkdir -p `dirname ${archive}`
 
     create_ufs "$archive" "$lofidev"
 
@@ -282,7 +179,7 @@ function create_archive
         ERROR=1
     else
         lockfs -f "/$OUT_DIR" 2>/dev/null
-        pfexec mv "${archive}-new" "$archive"
+        mv "${archive}-new" "$archive"
         lockfs -f "/$OUT_DIR" 2>/dev/null
     fi
 
@@ -295,9 +192,9 @@ function fatal_error
 }
 
 # Create tmp dir to do the work in
-rddir="/var/tmp/create_ramdisk.$$.tmp"
-pfexec rm -rf "$rddir"
-pfexec mkdir "$rddir" || fatal_error "Could not create temporary directory $rddir"
+rddir="/tmp/create_ramdisk.$$.tmp"
+rm -rf "$rddir"
+mkdir "$rddir" || fatal_error "Could not create temporary directory $rddir"
 
 # Clean up upon exit.
 trap 'cleanup' EXIT
@@ -307,15 +204,15 @@ rdmnt="$rddir/rd.mnt.32"
 lofidev=""
 
 echo "Creating ${SIZE}k ramdisk image: ${rdfile}" 
-pfexec mkfile ${SIZE}k "${rdfile}"
-pfexec chown ${USER} ${rdfile}
-lofidev32=`pfexec lofiadm -a "${rdfile}"`
+mkfile ${SIZE}k "${rdfile}"
+chown ${USER} ${rdfile}
+lofidev32=`lofiadm -a "${rdfile}"`
 create_archive "${OUT_DIR}/${BOOT_ARCHIVE_64}" $lofidev32
-pfexec mkdir -p `dirname ${OUT_DIR}/${OUT_KERNEL_64}`
-pfexec cp ${PROTO}/${KERNEL_64} ${OUT_DIR}/${OUT_KERNEL_64}
-pfexec lofiadm -d "$rdfile32" 2>/dev/null
-pfexec chmod 0644 ${OUT_DIR}/${BOOT_ARCHIVE_64}
-(cd ${OUT_DIR} && pfexec gtar -zcf ${PREFIX}.tgz ${PREFIX})
+mkdir -p `dirname ${OUT_DIR}/${OUT_KERNEL_64}`
+cp ${PROTO}/${KERNEL_64} ${OUT_DIR}/${OUT_KERNEL_64}
+lofiadm -d "$rdfile32" 2>/dev/null
+chmod 0644 ${OUT_DIR}/${BOOT_ARCHIVE_64}
+(cd ${OUT_DIR} && gtar -zcf ${PREFIX}.tgz ${PREFIX})
 
 if [ $ERROR = 1 ]; then
     cleanup
