OS-20 Add gzip support to gPXE or compress the image in some other way

diff --git a/tools/build_live b/tools/build_live
--- a/tools/build_live
+++ b/tools/build_live
@@ -37,12 +37,12 @@ ERROR=0
 PLATFORM=i86pc
 ISA=i386
 ARCH64=amd64
-SIZE=750000
+RSIZE=290000
+USIZE=425000
 BOOT_ARCHIVE_64=platform-${BUILDSTAMP}/$PLATFORM/$ARCH64/boot_archive
 OUT_KERNEL_64=platform-${BUILDSTAMP}/$PLATFORM/kernel/$ARCH64/unix
 KERNEL_64=platform/$PLATFORM/kernel/$ARCH64/unix
 PREFIX=platform-${BUILDSTAMP}
-compress=no
 
 if [ "$(id -u)" != "0" ]; then
   echo "You must have euid 0 to run this tool."
@@ -53,7 +53,6 @@ fi
 exec > >(tee ${LOGFILE}) 2>&1
 
 export PATH=/usr/sbin:/usr/bin:/sbin
-export GZIP_CMD=/usr/bin/gzip
 
 usage() {
     echo "This tool is for building a live boot_archive amd64."
@@ -118,13 +117,24 @@ function create_ufs
 {
     archive=$1
     lofidev=$2
+    lofiusrdev=$3
+    usrfile=$4
 
-    newfs ${lofidev} < /dev/null 2> /dev/null
+    newfs -o space -m 0 -i 32768 -b 4096 ${lofidev} < /dev/null 2> /dev/null
     mkdir "${rdmnt}"
     mount -F ufs -o nologging ${lofidev} "${rdmnt}"
 
+    newfs -o space -m 0 -i 8192 -b 4096 ${lofiusrdev} < /dev/null 2> /dev/null
+    mkdir "${rdmnt}/usr"
+    mount -F ufs -o nologging ${lofiusrdev} "${rdmnt}/usr"
+
     # do the actual copy
     ${BUILDER} ${MANIFEST} ${rdmnt} ${IN_DIRS}
+    if [ $? -ne 0 ]; then
+        echo "ERROR: copy onto the image failed, may need to increase the size"
+        ERROR=1
+	return
+    fi
     ${CUSTOMIZE_SCRIPT} ${rdmnt}
     ${SMF_IMPORTER} ${rdmnt}
 
@@ -140,10 +150,37 @@ function create_ufs
     mkdir -p `dirname ${OUT_DIR}/${OUT_KERNEL_64}`
     cp ${rdmnt}/${KERNEL_64} ${OUT_DIR}/${OUT_KERNEL_64}
 
+    # Set up the /usr files we need before /usr is mounted
+    echo "tmpdir $rddir/usr"
+    umount -f "$rdmnt/usr"
+    mkdir $rddir/usr
+    mount -F ufs -o nologging ${lofiusrdev} "${rddir}/usr"
+    (cd ${rddir}/usr && tar cbf 512 - \
+	bin/[ bin/cat bin/head bin/i86/ksh93 bin/ls kernel/sched/amd64/FSS \
+	lib/fm/libfmevent.so lib/fm/libfmevent.so.1 lib/fm/libtopo.so \
+	lib/fm/libtopo.so.1 lib/libast.so lib/libast.so.1 lib/libcmd.so \
+	lib/libcmd.so.1 lib/libdll.so lib/libdll.so.1 lib/libexacct.so \
+	lib/libexacct.so.1 lib/libfstyp.so lib/libfstyp.so.1 lib/libidmap.so \
+	lib/libidmap.so.1 lib/libipmi.so lib/libipmi.so.1 lib/libpkcs11.so \
+	lib/libpkcs11.so.1 lib/libpool.so lib/libpool.so.1 lib/libproject.so \
+	lib/libproject.so.1 lib/libshell.so lib/libshell.so.1 lib/libsmbios.so \
+	lib/libsmbios.so.1 lib/libsum.so lib/libsum.so.1 sbin/lofiadm) | \
+	(cd ${rdmnt}/usr; tar xbf 512 -)
+
+    umount -f "${rddir}/usr"
+
+    (cd $rdmnt/usr/bin && ln -s "i86/ksh93" $rdmnt/usr/bin/sh)
+
+    # Now lofi compress our /usr filesystem
+    echo "lofi compressing usr file system"
+    lofiadm -d "$lofiusrdev" 2>/dev/null
+    lofiadm -C $usrfile
+    mv $usrfile $rdmnt/usr.lgz
+
     umount -f "$rdmnt"
     rmdir "$rdmnt"
-    gzip "$rdfile" && mv "${rdfile}.gz" "${archive}-new"
 
+    mv "${rdfile}" "${archive}-new"
     if [ $? -ne 0 ] ; then
         rm -f "${archive}-new"
         rm -f "${archive}.manifest"
@@ -154,31 +191,20 @@ function create_archive
 {
     archive=$1
     lofidev=$2
+    lofiusrdev=$3
+    usrfile=$4
 
-    echo "creating ${archive} (${lofidev})"
+    echo "creating ${archive} (${lofidev}) (${lofiusrdev})"
     mkdir -p `dirname ${archive}`
 
-    create_ufs "$archive" "$lofidev"
+    create_ufs "$archive" "$lofidev" "$lofiusrdev" "$usrfile"
 
     # sanity check the archive before moving it into place
     #
     ARCHIVE_SIZE=`ls -l "${archive}-new" 2> /dev/null | nawk '{ print $5 }'`
-    if [ $compress = yes ]; then
-        #
-        # 'file' will report "English text" for uncompressed
-        # boot_archives.  Checking for that doesn't seem stable,
-        # so we just check that the file exists.
-        #
-        ls "${archive}-new" >/dev/null 2>&1
-    else
-        #
-        # the file type check also establishes that the
-        # file exists at all
-        #
-        LC_MESSAGES=C file "${archive}-new" | grep gzip > /dev/null
-    fi
+    ls "${archive}-new" >/dev/null 2>&1
 
-    if [ $? = 1 ] && [ -x $GZIP_CMD ] || [ "$ARCHIVE_SIZE" -lt 10000 ]
+    if [ $? -eq 1 -o "$ARCHIVE_SIZE" -lt 10000 ]
     then
         #
         # Two of these functions may be run in parallel.  We
@@ -231,14 +257,22 @@ trap 'cleanup' EXIT
 
 rdfile="$rddir/rd.file.32"
 rdmnt="$rddir/rd.mnt.32"
-lofidev=""
+usrfile="$rddir/usr.file"
 
-echo "Creating ${SIZE}k ramdisk image: ${rdfile}" 
-mkfile ${SIZE}k "${rdfile}"
+echo "Creating ${RSIZE}k ramdisk image: ${rdfile}" 
+mkfile ${RSIZE}k "${rdfile}"
 chown ${USER} ${rdfile}
+echo "Creating ${USIZE}k usr image: ${usrfile}" 
+mkfile ${USIZE}k "${usrfile}"
+chown ${USER} ${usrfile}
+
 lofidev32=`lofiadm -a "${rdfile}"`
-create_archive "${OUT_DIR}/${BOOT_ARCHIVE_64}" $lofidev32
+lofidevusr=`lofiadm -a "${usrfile}"`
+
+create_archive "${OUT_DIR}/${BOOT_ARCHIVE_64}" $lofidev32 $lofidevusr $usrfile
+
 lofiadm -d "$lofidev32" 2>/dev/null
+
 chmod 0644 ${OUT_DIR}/${BOOT_ARCHIVE_64}
 (cd ${OUT_DIR} && gtar -zcf ${PREFIX}.tgz ${PREFIX})
 
