OS-6944 live image build needs to expand ucode files Reviewed by: Jerry Jelinek <jerry.jelinek@joyent.com> Reviewed by: Patrick Mooney <patrick.mooney@joyent.com> Approved by: Patrick Mooney <patrick.mooney@joyent.com>

diff --git a/tools/build_live b/tools/build_live
--- a/tools/build_live
+++ b/tools/build_live
@@ -327,6 +327,38 @@ function bi_smf_seeds
 	bi_emit_done
 }
 
+#
+# The ucode files that are installed by illumos for both Intel and AMD
+# are versions that have all of the different processors combined into
+# one file. However, the ucode update logic in the OS needs that to be
+# expanded into a per-processor file which is normally done by ucodeadm
+# as part of setting up a boot archive. To make sure that microcode
+# updates can be applied we take care of setting this up here. Over
+# time, we should change this to do it as part of the illumos build
+# process and likely illumos should just deliver the decomposed files.
+#
+function bi_expand_ucode
+{
+	local ucodeadm="/usr/sbin/ucodeadm -i -R "
+	local ucode_root="$bi_mnt_root/platform/i86pc/ucode"
+	local intc_file="$ucode_root/intel-ucode.txt"
+	local intc_dir="GenuineIntel"
+	local amd_file="$ucode_root/amd-ucode.bin"
+	local amd_dir="AuthenticAMD"
+
+	bi_emit_start 'Generating microcode files'
+
+	if ! pfexec $ucodeadm $ucode_root/$intc_dir $intc_file; then
+		fail "failed to generate Intel microcode files"
+	fi
+
+	if ! pfexec $ucodeadm $ucode_root/$amd_dir $amd_file; then
+		fail "failed to generate AMD microcode files"
+	fi
+
+	bi_emit_done
+}
+
 function bi_create_password
 {
 	local pwgen="$bi_wsroot/tools/pwgen"
@@ -925,6 +957,7 @@ bi_copy_files
 bi_gen_whatis
 bi_smf_import
 bi_smf_seeds
+bi_expand_ucode
 bi_create_password
 bi_gen_etcrelease
 bi_gen_buildstamp_module
