more code review

diff --git a/tools/build_boot_image b/tools/build_boot_image
--- a/tools/build_boot_image
+++ b/tools/build_boot_image
@@ -11,7 +11,7 @@
 #
 
 #
-# Copyright (c) 2018, Joyent, Inc.
+# Copyright (c) 2019, Joyent, Inc.
 #
 
 #
@@ -43,18 +43,17 @@
 bi_console="text"
 bi_make_iso=0
 bi_proforma_only=0
-bi_ufs_root=0
 bi_nocleanup=0
 bi_imgsz_gb="2"
 bi_imgsz=$(( $bi_imgsz_gb * 1000000000 ))
 bi_wsroot=
-lofi_blkdev=
-lofi_rawdev=
-esp_blkdev=
-usb_image_name=
-rootdir=
-efimnt=
-tmpdir=
+bi_lofi_blkdev=
+bi_lofi_rawdev=
+bi_esp_blkdev=
+bi_usb_image_name=
+bi_rootdir=
+bi_efimnt=
+bi_tmpdir=
 
 function detach_lofi()
 {
@@ -77,28 +76,29 @@ function cleanup()
 
 	print "Cleaning up"
 
-	if mount | grep $efimnt >/dev/null; then
-		pfexec umount $efimnt
+	if mount | grep $bi_efimnt >/dev/null; then
+		pfexec umount $bi_efimnt
 	fi
 
-	if mount | grep $rootdir >/dev/null; then
-		pfexec umount $rootdir
+	if mount | grep $bi_rootdir >/dev/null; then
+		pfexec umount $bi_rootdir
 	fi
 
-	detach_lofi "$lofi_blkdev"
-	detach_lofi "$esp_blkdev"
+	detach_lofi "$bi_lofi_blkdev"
+	detach_lofi "$bi_esp_blkdev"
 
-	pfexec rm -f $tmpdir/esp.img
-	pfexec rm -f $tmpdir/rootfs.img
-	pfexec rm -f $tmpdir/smartos.usb
-	pfexec rm -f $tmpdir/partition.map
-	pfexec rm -rf $tmpdir/mnt
-	pfexec rmdir $tmpdir
+	pfexec rm -f $bi_tmpdir/esp.img
+	pfexec rm -f $bi_tmpdir/rootfs.img
+	pfexec rm -f $bi_tmpdir/smartos.usb
+	pfexec rm -f $bi_tmpdir/partition.map
+	pfexec rm -f $bi_tmpdir/loader.conf
+	pfexec rm -rf $bi_tmpdir/mnt
+	pfexec rmdir $bi_tmpdir
 }
 
 function fail()
 {
-        printf "$0: %s\n" "$1" 1>&2
+        printf "$(basename $0): %s\n" "$1" 1>&2
         exit 1
 }
 
@@ -106,9 +106,8 @@ function usage()
 {
 	[[ ! -z $1 ]] && printf "%s\n\n" "$1" 1>&2
 
-	print -u2 "Usage: $0 [-U] [-I] [-x] [-c console] " \
+	print -u2 "Usage: $(basename $0) [-I] [-x] [-c console] " \
 	    "[-p <size>] -r <smartos-live repo>"
-	print -u2 "\n -U\tcreate UFS filesystem on root partition (default: PCFS)"
 	print -u2 " -I\tbuild SmartOS ISO image (default: USB image)"
 	print -u2 " -c\tspecify primary console (e.g. ttyb)"
 	print -u2 " -p\tbuild proforma USB image for Triton (e.g. 1gb)"
@@ -140,20 +139,20 @@ function create_esp()
 	local readonly esp_sects=$(( $esp_size * 1024 * 1024 / 512 ))
 
 	pfrun mkfile -n ${esp_size}m $tmpdir/esp.img
-	esp_blkdev=$(pfexec lofiadm -a $tmpdir/esp.img)
+	bi_esp_blkdev=$(pfexec lofiadm -a $tmpdir/esp.img)
 	[[ $? == 0 ]] || fail "Failed to create ESP lofi device"
-	readonly esp_rawdev=${esp_blkdev/lofi/rlofi}
+	readonly esp_rawdev=${bi_esp_blkdev/lofi/rlofi}
 
 	pfrun mkfs -F pcfs -o b=system,size=$esp_sects,nofdisk,fat=32 \
 	    $esp_rawdev </dev/null
 
 	pfrun mkdir -p $efimnt
-	pfrun mount -F pcfs -o foldcase $esp_blkdev $efimnt
+	pfrun mount -F pcfs -o foldcase $bi_esp_blkdev $efimnt
 	pfrun mkdir -p $efimnt/efi/boot
 	pfrun cp $bi_wsroot/proto.boot/boot/loader64.efi \
 	    $efimnt/efi/boot/bootx64.efi
 	pfrun umount $efimnt
-	pfrun lofiadm -d $esp_blkdev
+	pfrun lofiadm -d $bi_esp_blkdev
 }
 
 #
@@ -178,9 +177,7 @@ function populate_root()
 		exit 1 ;;
 	esac
 
-	pfrun touch $dir/boot/loader.conf
-	pfrun chmod 644 $dir/boot/loader.conf
-	pfrun cat <<EOF >$dir/boot/loader.conf
+	cat <<EOF >$bi_tmpdir/loader.conf
 console="$console"
 os_console="$bi_console"
 ttya-mode="115200,8,n,1,-"
@@ -192,6 +189,8 @@ loader_brand="smartos"
 root_shadow="${shadow}"
 smartos="true"
 EOF
+	pfrun mv $bi_tmpdir/loader.conf $dir/boot/loader.conf
+	pfrun chmod 644 $dir/boot/loader.conf
 	print "done"
 
 	print "Copying platform image to root partition" \
@@ -212,18 +211,18 @@ function create_iso()
 	local readonly espimg=$3
 
 	pfrun mkdir -p $bi_wsroot/output-iso
-	pfrun mkdir -p $rootdir
+	pfrun mkdir -p $bi_rootdir
 
-	populate_root $rootdir
+	populate_root $bi_rootdir
 
-	pfrun cp $bi_wsroot/proto/boot/cdboot $rootdir/boot/cdboot
-	pfrun cp $espimg $rootdir/boot/efiboot.img
+	pfrun cp $bi_wsroot/proto/boot/cdboot $bi_rootdir/boot/cdboot
+	pfrun cp $espimg $bi_rootdir/boot/efiboot.img
 
 	pfrun mkisofs -quiet -R \
 	    -eltorito-boot boot/cdboot -no-emul-boot -boot-info-table \
 	    -eltorito-alt-boot -eltorito-platform efi \
 	    -eltorito-boot boot/efiboot.img -no-emul-boot \
-	    -o $iso $rootdir
+	    -o $iso $bi_rootdir
 
 	print "Successfully created $iso"
 }
@@ -240,15 +239,15 @@ function create_image()
 
 	pfrun mkfile -n $size $file
 
-	lofi_blkdev=$(pfexec lofiadm -a $file)
+	bi_lofi_blkdev=$(pfexec lofiadm -a $file)
 	[[ $? == 0 ]] || fail "Failed to create lofi device"
 
 	pfrun $bi_wsroot/tools/format_image/format_image \
 	    -m $bi_wsroot/proto.boot/boot/pmbr \
 	    -b $bi_wsroot/proto.boot/boot/gptzfsboot -e $tmpdir/esp.img \
-	    -o ${lofi_blkdev/lofi/rlofi} >$tmpdir/partition.map
+	    -o ${bi_lofi_blkdev/lofi/rlofi} >$tmpdir/partition.map
 
-	pfrun lofiadm -d $lofi_blkdev
+	pfrun lofiadm -d $bi_lofi_blkdev
 }
 
 #
@@ -261,14 +260,9 @@ function create_root()
 	local readonly offset=$3
 	local readonly sects=$(( $4 / 512 ))
 
-	if [[ $bi_ufs_root == 1 ]]; then
-		print "Creating UFS filesystem in root partition ... \c"
-		pfexec newfs $dev </dev/null
-	else
-		print "Creating PCFS filesystem in root partition ... \c"
-		pfrun mkfs -F pcfs -o b=SMARTOSBOOT,size=$sects,nofdisk,fat=32 \
-		    $dev </dev/null
-	fi
+	print "Creating PCFS filesystem in root partition ... \c"
+	pfrun mkfs -F pcfs -o b=SMARTOSBOOT,size=$sects,nofdisk,fat=32 \
+	    $dev </dev/null
 
 	print "done"
 
@@ -301,10 +295,6 @@ function mount_root()
 	local readonly rootmnt=$2
 	local mntopts="-F pcfs"
 
-	if [[ $bi_ufs_root == 1 ]]; then
-		mntopts="-o nologging"
-	fi
-
 	print "Mounting root partition at $rootmnt ... \c"
 	pfrun mkdir -p $rootmnt
 	pfrun mount $mntopts $dev $rootmnt 2>/dev/null
@@ -320,20 +310,19 @@ function copy_results()
 	local readonly gid=$(id -g)
 
 	mkdir -p $outdir
-	pfrun mv $tmpdir/smartos.usb $outdir/$outfile
+	pfrun mv $bi_tmpdir/smartos.usb $outdir/$outfile
 	pfrun chmod 644 $outdir/$outfile
 	pfrun chown ${uid}:${gid} $outdir/$outfile
-	pfrun cp $tmpdir/partition.map $outdir/${prefix}partition.map
+	pfrun cp $bi_tmpdir/partition.map $outdir/${prefix}partition.map
 	pfrun chown ${uid}:${gid} $outdir/${prefix}partition.map
 	print "Successfully created $outdir/$outfile"
 }
 
 export PATH=/usr/bin/:/usr/sbin/:/opt/local/bin
 
-while getopts "IUc:p:r:x" c $@; do
+while getopts "Ic:p:r:x" c $@; do
 	case "$c" in
 	I)	bi_make_iso=1 ;;
-	U)	bi_ufs_root=1 ;;
 	c)	bi_console=${OPTARG} ;;
 	p)	bi_proforma_only=1
 		bi_imgsz_gb=${OPTARG%gb}
@@ -351,9 +340,6 @@ unalias -a
 
 [[ -z "$bi_wsroot" ]] && usage "-r is required"
 
-[[ $bi_proforma_only == 1 ]] && [[ $bi_ufs_root == 1 ]] && \
-    usage "-p and -U are mutually exclusive"
-
 [[ $bi_proforma_only == 1 ]] && [[ $bi_make_iso == 1 ]] && \
     usage "-p and -I are mutually exclusive"
 
@@ -361,62 +347,62 @@ unalias -a
     fail "No platform image found in $bi_wsroot/output"
 
 
-tmpdir=$(mktemp -d -p /var/tmp) || fail "mktemp failed!"
+bi_tmpdir=$(mktemp -d -p /var/tmp) || fail "mktemp failed!"
 
 trap cleanup EXIT
 
-efimnt=$tmpdir/mnt/efi
-rootdir=$tmpdir/mnt/root
-usb_image_name=$(readlink -f $bi_wsroot/output/platform-latest)
-usb_image_name=$(basename $usb_image_name)
-iso_image_name="$bi_wsroot/output-iso/${usb_image_name}.iso"
-usb_image_name="${usb_image_name}.usb"
+bi_efimnt=$bi_tmpdir/mnt/efi
+bi_rootdir=$bi_tmpdir/mnt/root
+bi_usb_image_name=$(readlink -f $bi_wsroot/output/platform-latest)
+bi_usb_image_name=$(basename $bi_usb_image_name)
+iso_image_name="$bi_wsroot/output-iso/${bi_usb_image_name}.iso"
+bi_usb_image_name="${bi_usb_image_name}.usb"
 
 print "Creating EFI System Partition image ... \c"
-create_esp $tmpdir $efimnt
+create_esp $bi_tmpdir $bi_efimnt
 print "done"
 
 if [[  $bi_make_iso == 1 ]]; then
-	create_iso $tmpdir $iso_image_name $tmpdir/esp.img
+	create_iso $bi_tmpdir $iso_image_name $bi_tmpdir/esp.img
 	exit 0
 fi
 
-print "Creating $bi_imgsz_gb GB image at $tmpdir/smartos.usb ... \c"
-create_image $tmpdir $bi_imgsz $tmpdir/smartos.usb
+print "Creating $bi_imgsz_gb GB image at $bi_tmpdir/smartos.usb ... \c"
+create_image $bi_tmpdir $bi_imgsz $bi_tmpdir/smartos.usb
 print "done"
 
 echo "partition.map:"
-cat $tmpdir/partition.map
+cat $bi_tmpdir/partition.map
 
-rootoff=$(nawk '$1 == "root" { print $3 }' <$tmpdir/partition.map)
-rootsize=$(nawk '$1 == "root" { print $4 }' <$tmpdir/partition.map)
+rootoff=$(nawk '$1 == "root" { print $3 }' <$bi_tmpdir/partition.map)
+rootsize=$(nawk '$1 == "root" { print $4 }' <$bi_tmpdir/partition.map)
 
-pfrun mkfile -n $rootsize $tmpdir/rootfs.img
+pfrun mkfile -n $rootsize $bi_tmpdir/rootfs.img
 
-lofi_blkdev=$(pfexec lofiadm -a $tmpdir/rootfs.img)
+bi_lofi_blkdev=$(pfexec lofiadm -a $bi_tmpdir/rootfs.img)
 [[ $? == 0 ]] || fail "Failed to create lofi device"
 
-lofi_rawdev=${lofi_blkdev/lofi/rlofi}
+bi_lofi_rawdev=${bi_lofi_blkdev/lofi/rlofi}
 
-create_root $lofi_rawdev $tmpdir/smartos.usb $rootoff $rootsize
+create_root $bi_lofi_rawdev $bi_tmpdir/smartos.usb $rootoff $rootsize
 
 #
 # The proforma image's root partition is populated by sdc-headnode, not us.
 #
 if [[ $bi_proforma_only != 1 ]]; then
-	mount_root $lofi_blkdev $rootdir
-	populate_root $rootdir
-	pfrun umount $rootdir
+	mount_root $bi_lofi_blkdev $bi_rootdir
+	populate_root $bi_rootdir
+	pfrun umount $bi_rootdir
 fi
 
-copy_root $lofi_rawdev $tmpdir/smartos.usb $rootoff
+copy_root $bi_lofi_rawdev $bi_tmpdir/smartos.usb $rootoff
 
-pfrun lofiadm -d $lofi_blkdev
+pfrun lofiadm -d $bi_lofi_blkdev
 
 if [[ $bi_proforma_only == 1 ]]; then
 	copy_results $bi_wsroot/proto.images ${bi_imgsz_gb}gb.img ${bi_imgsz_gb}gb.
 else
-	copy_results $bi_wsroot/output-usb $usb_image_name ""
+	copy_results $bi_wsroot/output-usb $bi_usb_image_name ""
 fi
 
 exit 0
