OS-496 Add missing packages to configure for building in a zone OS-490 Remove pieces that require libmeta from the build and live image OS-487 illumos-live/src_addon Makefile should not ignore failure OS-497 ipmi Makefile should be updated so it builds in a zone OS-488 tools/build_live should bail if tools/smf_import fails OS-489 tools/smf_import shouldn't use system svccfg

diff --git a/tools/build_live b/tools/build_live
--- a/tools/build_live
+++ b/tools/build_live
@@ -150,7 +150,12 @@ function create_ufs
 	return
     fi
     ${CUSTOMIZE_SCRIPT} ${rdmnt} ${BUILDSTAMP}
-    ${SMF_IMPORTER} ${rdmnt}
+    ROOT=${ROOT} ${SMF_IMPORTER} ${rdmnt}
+    if [ $? -ne 0 ]; then
+	echo "ERROR: setting up live image SMF repoistory failed"
+	ERROR=1
+	return
+    fi
 
     echo "Setting root password..."
     create_password "${rdmnt}"
diff --git a/tools/smf_import b/tools/smf_import
--- a/tools/smf_import
+++ b/tools/smf_import
@@ -5,11 +5,23 @@
 
 set -e
 
+SVCCFG="${ROOT}/projects/illumos/usr/src/cmd/svc/svccfg/svccfg-native"
+
 rdmnt=$1
 if [ -z "${rdmnt}" ] || [ ! -d "${rdmnt}" ]; then
   echo "FATAL: Invalid ramdisk root '${rdmnt}'"
   echo "Usage: $0 <rdmnt>"
   exit 1
+fi
+
+if [ -z "${ROOT}" ]; then
+	echo "FATAL: ROOT not specified"
+	exit 1
+fi
+
+if [[ ! -x ${SVCCFG} ]]; then
+	echo "FATAL: Missing svccfg-native binary from illumos build looked in '${SVCCFG}'"
+	exit 1
 fi
 
 # TODO check that we're root
@@ -21,7 +33,6 @@ export SVCCFG_DTD=${rdmnt}/usr/share/lib/xml/dtd/service_bundle.dtd.1
 export SVCCFG_REPOSITORY=${REPO_DB}
 export SVCCFG_CONFIGD_PATH=/lib/svc/bin/svc.configd
 
-SVCCFG="/usr/sbin/svccfg"
 ${SVCCFG} -v repository ${REPO_DB}
 ${SVCCFG} -v add smf/manifest
 ${SVCCFG} -v import ${rdmnt}/lib/svc/manifest
