rework

diff --git a/tools/build_ctftools b/tools/build_ctftools
--- a/tools/build_ctftools
+++ b/tools/build_ctftools
@@ -14,51 +14,141 @@
 # Copyright 2020 Joyent, Inc.
 #
 
-# Setup for building stuff!
-unset CC
-unset CXX
-ROOT=`pwd`
-export PATH=/opt/onbld/bin:/sbin:/usr/sbin:/usr/bin:/usr/ccs/bin:/opt/SUNWspro/bin:/opt/local/bin
-export SHELL=/usr/bin/bash
-
-export CTFTOOLS_TARBALL=$1
-
-mkdir -p ${ROOT}/proto
-if [[ ! -f ${ROOT}/proto/buildstamp ]]; then
-    if [[ -z $BUILDSTAMP ]]; then
-        BUILDSTAMP=$(TZ=UTC date "+%Y%m%dT%H%M%SZ"); export BUILDSTAMP
-    fi
-    echo "${BUILDSTAMP}" > ${ROOT}/proto/buildstamp
-else
-    BUILDSTAMP=$(<${ROOT}/proto/buildstamp)
-    if [[ $? -ne 0 || -z "${BUILDSTAMP}" ]]; then
-        printf "failed to read existing buildstamp\n" >&2
+function fatal
+{
+        local msg="$*"
+        [[ -z "$msg" ]] && msg="failed"
+        echo "$msg" >&2
         exit 1
-    fi
-fi
+}
 
-echo "==> Building ctftools tarball (${BUILDSTAMP})"
+function verbose
+{
+	echo "$@"
+	"$@"
+}
 
+function make
+{
+	local max_jobs=128
+	local tarball=""
+
+	# Setup for building stuff!
+	unset CC
+	unset CXX
+	ROOT=`pwd`
+	export PATH=/opt/onbld/bin:/sbin:/usr/sbin:/usr/bin:/usr/ccs/bin:/opt/SUNWspro/bin:/opt/local/bin
+	export SHELL=/usr/bin/bash
+
+	while getopts "hj:o:" arg; do
+		case $arg in
+		h)
+			echo "$usage"
+			exit 0 ;;
+		j)
+			max_jobs=$OPTARG ;;
+		o)
+			export CTFTOOLS_TARBALL=$OPTARG ;;
+		?)
+			echo "$usage" >&2
+			exit 1 ;;
+		esac
+	done
+
+	[[ -n "$CTFTOOLS_TARBALL" ]] || fatal "missing -o argument"
+
+	mkdir -p ${ROOT}/proto
+	if [[ ! -f ${ROOT}/proto/buildstamp ]]; then
+		if [[ -z $BUILDSTAMP ]]; then
+			export BUILDSTAMP=$(TZ=UTC date "+%Y%m%dT%H%M%SZ")
+		fi
+		echo "${BUILDSTAMP}" > ${ROOT}/proto/buildstamp
+	else
+		BUILDSTAMP=$(<${ROOT}/proto/buildstamp)
+		if [[ $? -ne 0 || -z "${BUILDSTAMP}" ]]; then
+			printf "failed to read existing buildstamp\n" >&2
+			exit 1
+		fi
+	fi
+
+	echo "==> Building ctftools tarball (${BUILDSTAMP})"
+
+	mkdir -p "$(dirname $CTFTOOLS_TARBALL)"
+
+	cd ${ROOT}/projects/illumos
+	[[ -d "log" ]] || mkdir -p log
+	gsed -i -e "s|^GATE=.*$|GATE=\"joyent_${BUILDSTAMP}\"; export GATE|" illumos.sh
+	gsed -i -e "s|^MAX_JOBS=.*$|MAX_JOBS=${max_jobs}; export MAX_JOBS|" illumos.sh
+
+	#
+	# illumos.sh sets the value of $MAKE by default, which is used by bldenv
+	# and nightly. By setting MAKE below to the bootstrap dmake, illumos.sh
+	# will honor the one in the environment and let us solve the chicken and
+	# egg problem that we have.
+	#
+	export MAKE=/opt/local/bin/dmake
+	./usr/src/tools/scripts/bldenv illumos.sh \
+	    'cd $CODEMGR_WS/usr/src && export PATH="$PATH:/opt/local/bin" && \
+	    dmake setup && cd tools/ctf && dmake ctftools'
+}
+
+#
+# Upload a ctftools tarball.
+#
+function upload
+{
+	local bits_dir=""
+	local upload_dir=""
+	local platform=""
+	local timestamp=""
+
+	while getopts "D:d:hp:t:" arg; do
+		case $arg in
+		D)
+			bits_dir=$OPTARG ;;
+		d)
+			upload_dir=$OPTARG ;;
+		h)
+			echo "$usage"
+			exit 0 ;;
+		p)
+			platform=$OPTARG ;;
+		t)
+			timestamp=$OPTARG ;;
+		?)
+			echo "$usage" >&2
+			exit 1 ;;
+		esac
+	done
+
+	[[ -n "$bits_dir" ]] || fatal "missing -D argument"
+	[[ -n "$upload_dir" ]] || fatal "missing -d argument"
+	[[ -n "$platform" ]] || fatal "missing -p argument"
+	[[ -n "$timestamp" ]] || fatal "missing -t argument"
+
+	mdir="/$MANTA_USER/$upload_dir/built.$platform/"
+	mbdir="$mdir/$timestamp"
+
+	verbose mmkdir -p "$mbdir"
+
+	for file in $bits_dir/*; do
+		verbose mput -f "$file" "$mbdir/$(basename $file)"
+	done
+
+	echo "$mbdir" | mput -H "content-type: text/plain" "$mdir/latest"
+}
+
+export PATH=/usr/bin:/usr/sbin:/sbin:/opt/local/bin:/opt/local/sbin
 set -o pipefail
 set -e
 
-cd ${ROOT}/projects/illumos
-[[ -d "log" ]] || mkdir -p log
-gsed -i -e "s|^GATE=.*$|GATE=\"joyent_${BUILDSTAMP}\"; export GATE|" illumos.sh
-if [[ -n ${MAX_JOBS} ]]; then
-    MJ=${MAX_JOBS}
-else
-    MJ=128
-fi
-gsed -i -e "s|^MAX_JOBS=.*$|MAX_JOBS=${MJ}; export MAX_JOBS|" illumos.sh
+cmd=$1
+shift
 
-#
-# illumos.sh sets the value of $MAKE by default, which is used by bldenv
-# and nightly. By setting MAKE below to the bootstrap dmake, illumos.sh
-# will honor the one in the environment and let us solve the chicken and
-# egg problem that we have.
-#
-export MAKE=/opt/local/bin/dmake
-./usr/src/tools/scripts/bldenv illumos.sh \
-    'cd $CODEMGR_WS/usr/src && export PATH="$PATH:/opt/local/bin" && \
-    dmake setup && cd tools/ctf && dmake ctftools'
+case $cmd in
+	make) make $* ;;
+	upload) upload $* ;;
+	*)
+		echo "$usage" >&2
+		exit 1 ;;
+esac
diff --git a/tools/build_strap b/tools/build_strap
--- a/tools/build_strap
+++ b/tools/build_strap
@@ -27,21 +27,21 @@
 # we'll fall back to doing a full strap build of illumos-extra.  This is also
 # true if the user specified non-default compilers.
 #
-# The -l and -t options are used when building and uploading a new cache.
+# The -u, -D, and -t options are used when building and uploading a strap cache
+# tarball.
 #
 
-usage="$0 [-l | -a adjunct.tar [-f] [-j maxjobs] [-t tarfile | -d protodir]]"
+usage="$0 build -a adjunct.tar -j maxjobs -d protodir [-f] [-o tarball]"
+usage="$usage | upload -D bits -d path -t timestamp ]-u path -d inpath -t timestamp"
 wsroot=$(cd $(dirname $0)/../; pwd)
 pkgin_file="/opt/local/etc/pkgin/repositories.conf"
-manta_dir="/Joyent_Dev/public/SmartOS/build-cache/master"
-manta_base="https://us-east.manta.joyent.com/$manta_dir"
+manta_dir="/Joyent_Dev/public/builds/SmartOS/strap-cache/master"
 cache_base="/opt/SmartOS/build-cache/"
 srcdir="$wsroot/projects/illumos-extra"
 adjunct=""
 protodir=""
 max_jobs="128"
 force_build="no"
-report_loc="no"
 tarfile=""
 
 function fatal
@@ -104,20 +104,26 @@ function download
 	local srcdirsha=$2
 	local cache_dir="$cache_base/$pkgsrc_branch/$srcdirsha"
 	local outfile="/var/tmp/$srcdirsha.proto.strap.tar.gz.$$"
-	local url="$manta_base/$pkgsrc_branch/$srcdirsha/proto.strap.tar.gz"
 	local tmpdir="$cache_dir.$$"
-
-	pfexec mkdir -p "$tmpdir" || fatal "failed to make $cache_dir"
+	local latest="$manta_dir/$pkgsrc_branch/$srcdirsha/latest"
+	local url="$(mget -q $latest 2>/dev/null)"
 
 	echo "Downloading proto.strap contents from $url ..."
 
+	if [[ -z "$url" ]]; then
+		echo "Failed to find $latest: building locally"
+		build_strap
+		return 0
+	fi
+
 	if ! curl -f -o "$outfile" "$url"; then
 		rm -f "$outfile"
-		pfexec rm -rf "$tmpdir"
 		echo "Failed to download $url: building locally"
 		build_strap
 		return 0
 	fi
+
+	pfexec mkdir -p "$tmpdir" || fatal "failed to make $tmpdir"
 
 	if ! pfexec tar xzf "$outfile" -C "$tmpdir"; then
 		rm -f "$outfile"
@@ -161,6 +167,9 @@ function create_cache
 		build_strap
 	fi
 
+	mkdir -p $(dirname $tarfile) ||
+	    fatal "failed to mkdir for $tarfile"
+
 	pfexec gtar -C "$cache_dir" -czf "$tarfile" . ||
 	    fatal "failed to create $tarfile"
 
@@ -176,9 +185,35 @@ function create_cache
 #
 function populate_strap
 {
-	local pkgsrc_branch=$1
-	local srcdirsha=$2
+	local pkgsrc_branch=$(identify_pkgsrc_branch)
+	local srcdirsha=$(identify_srcsha)
 	local cache_dir="$cache_base/$pkgsrc_branch/$srcdirsha"
+
+	set -x
+
+	while getopts "a:d:fhlj:o:" arg; do
+		case $arg in
+		a)
+			adjunct=$OPTARG ;;
+		d)
+			protodir=$OPTARG ;;
+		f)
+			force_build=yes ;;
+		h)
+			echo "$usage"
+			exit 0 ;;
+		j)
+			max_jobs=$OPTARG ;;
+		o)
+			tarfile=$OPTARG ;;
+		?)
+			echo "$usage" >&2
+			exit 1 ;;
+		esac
+	done
+
+	[[ -n "$adjunct" ]] || fatal "missing -a argument"
+	[[ -n "$protodir" ]] || fatal "missing -d argument"
 
 	if [[ -e "$cache_dir" && ! -d "$cache_dir" ]]; then
 		fatal "found weird non-directory $cache_dir"
@@ -216,47 +251,61 @@ function populate_strap
 
 }
 
+#
+# Upload a proto.strap tarball.
+#
+function upload_strap
+{
+	local pkgsrc_branch=$(identify_pkgsrc_branch)
+	local srcdirsha=$(identify_srcsha)
+	local bits_dir=""
+	local upload_dir=""
+	local timestamp=""
+
+	while getopts "D:d:ht:" arg; do
+		case $arg in
+		D)
+			bits_dir=$OPTARG ;;
+		d)
+			upload_dir=$OPTARG ;;
+		t)
+			timestamp=$OPTARG ;;
+		h)
+			echo "$usage"
+			exit 0 ;;
+		?)
+			echo "$usage" >&2
+			exit 1 ;;
+		esac
+	done
+
+	[[ -n "$bits_dir" ]] || fatal "missing -D argument"
+	[[ -n "$upload_dir" ]] || fatal "missing -d argument"
+	[[ -n "$timestamp" ]] || fatal "missing -t argument"
+
+	mdir="/$MANTA_USER/$upload_dir/$pkgsrc_branch/$srcdirsha/"
+	mbdir="$mdir/$timestamp"
+
+	verbose mmkdir -p "$mbdir"
+
+	for file in $bits_dir/*; do
+		verbose mput -f $file $mbdir/$(basename $file)
+	done
+
+	echo $mbdir | mput -H "content-type: text/plain" "$mdir/latest"
+}
+
 export PATH=/usr/bin:/usr/sbin:/sbin:/opt/local/bin:/opt/local/sbin
 set -o pipefail
+set -e
 
-while getopts "a:d:fhlj:t:" arg; do
-	case $arg in
-	a)
-		adjunct=$OPTARG ;;
-	d)
-		protodir=$OPTARG ;;
-	f)
-		force_build=yes ;;
-	h)
-		echo "$usage"
-		exit 0 ;;
-	j)
-		max_jobs=$OPTARG ;;
-	l)
-		report_loc="yes" ;;
-	t)
-		tarfile=$OPTARG ;;
-	?)
+cmd=$1
+shift
+
+case $cmd in
+	make) populate_strap $* ;;
+	upload) upload_strap $* ;;
+	*)
 		echo "$usage" >&2
 		exit 1 ;;
-	esac
-done
-
-if [[ "$report_loc" = "yes" ]]; then
-	echo $(identify_pkgsrc_branch)/$(identify_srcsha)
-	exit 0
-fi
-
-[[ -n "$adjunct" ]] || fatal "missing -a argument"
-[[ -d "$srcdir" ]] || fatal "cannot find illumos-extra in $srcdir"
-[[ -d "$srcdir/.git" ]] || fatal "$srcdir is not a git repo"
-
-if [[ -n "$tarfile" ]]; then
-	[[ -z "$protodir" ]] || fatal "can't specify -n and -d"
-else
-	[[ -n "$protodir" ]] || fatal "missing -d argument"
-fi
-
-populate_strap $(identify_pkgsrc_branch) $(identify_srcsha)
-
-exit 0
+esac
