August 12, 2011 Update

diff --git a/tools/build_live b/tools/build_live
--- a/tools/build_live
+++ b/tools/build_live
@@ -21,11 +21,10 @@
 #
 
 # Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
-# Copyright 2010 Joyent, Inc.  All rights reserved.
+# Copyright 2010, 2011 Joyent, Inc.  All rights reserved.
 # Use is subject to license terms.
 
 ROOT=`pwd`
-MAN_DIR=${ROOT}/projects/opensolaris-man
 CUSTOMIZE_SCRIPT=${ROOT}/tools/customize
 SMF_IMPORTER=${ROOT}/tools/smf_import
 BUILDER=${ROOT}/tools/builder/builder
@@ -43,8 +42,8 @@ ERROR=0
 PLATFORM=i86pc
 ISA=i386
 ARCH64=amd64
-RSIZE=264000
-USIZE=400000
+RSIZE=272000
+USIZE=390000
 KERNEL_64=platform/$PLATFORM/kernel/$ARCH64/unix
 BUILDVER=$(head -n1 ${ROOT}/configure-buildver)
 if [[ -n "${BUILDVER}" ]]; then
@@ -120,8 +119,10 @@ echo "=== /Options ==="
 
 function cleanup
 {
+    umount -f "${rdmnt}/usr" 2>/dev/null
     umount -f "${rdmnt}" 2>/dev/null
     lofiadm -d "${rdfile}" 2>/dev/null
+    lofiadm -d "${usrfile}" 2>/dev/null
     [ -n "${rddir}" ] && rm -fr "${rddir}" 2> /dev/null
 }
 
@@ -143,12 +144,18 @@ function create_ufs
     # do the actual copy
     ${BUILDER} ${MANIFEST} ${rdmnt} ${IN_DIRS}
     if [ $? -ne 0 ]; then
-        echo "ERROR: copy onto the image failed, may need to increase the size"
+        echo "ERROR: copy onto the image failed"
+        echo "(may need to increase the size or manifest file not found)"
         ERROR=1
 	return
     fi
     ${CUSTOMIZE_SCRIPT} ${rdmnt} ${BUILDSTAMP}
-    ${SMF_IMPORTER} ${rdmnt}
+    ROOT=${ROOT} ${SMF_IMPORTER} ${rdmnt}
+    if [ $? -ne 0 ]; then
+	echo "ERROR: setting up live image SMF repoistory failed"
+	ERROR=1
+	return
+    fi
 
     echo "Setting root password..."
     create_password "${rdmnt}"
@@ -214,6 +221,8 @@ function create_archive
     mkdir -p `dirname ${archive}`
 
     create_ufs "$archive" "$lofidev" "$lofiusrdev" "$usrfile"
+    [ $ERROR -eq 1 ] && return
+
 
     # sanity check the archive before moving it into place
     #
@@ -288,10 +297,15 @@ create_archive "${OUT_DIR}/${BOOT_ARCHIVE_64}" $lofidev32 $lofidevusr $usrfile
 
 lofiadm -d "$lofidev32" 2>/dev/null
 
-chmod 0644 ${OUT_DIR}/${BOOT_ARCHIVE_64}
-(cd ${OUT_DIR} && gtar -zcf ${PREFIX}.tgz ${PREFIX})
+if [ $ERROR -eq 0 ]; then
+    chmod 0644 ${OUT_DIR}/${BOOT_ARCHIVE_64}
+    echo "${BUILDSTAMP}" > ${OUT_DIR}/buildstamp
+    (cd ${OUT_DIR} && gtar -zcf ${PREFIX}.tgz ${PREFIX})
+fi
 
-if [ $ERROR = 1 ]; then
+if [ $ERROR -eq 1 ]; then
     cleanup
     exit 1
 fi
+
+exit 0
diff --git a/tools/smf_import b/tools/smf_import
--- a/tools/smf_import
+++ b/tools/smf_import
@@ -1,34 +1,27 @@
 #!/bin/bash
 #
-# CDDL HEADER START
-#
-# The contents of this file are subject to the terms of the
-# Common Development and Distribution License, Version 1.0 only
-# (the "License").  You may not use this file except in compliance
-# with the License.
-#
-# You can obtain a copy of the license at COPYING
-# See the License for the specific language governing permissions
-# and limitations under the License.
-#
-# When distributing Covered Code, include this CDDL HEADER in each
-# file and include the License file at COPYING.
-# If applicable, add the following below this CDDL HEADER, with the
-# fields enclosed by brackets "[]" replaced with your own identifying
-# information: Portions Copyright [yyyy] [name of copyright owner]
-#
-# CDDL HEADER END
-#
-# Copyright (c) 2010,2011 Joyent Inc.
+# Copyright (c) 2010 Joyent Inc., All rights reserved.
 #
 
 set -e
+
+SVCCFG="${ROOT}/projects/illumos/usr/src/cmd/svc/svccfg/svccfg-native"
 
 rdmnt=$1
 if [ -z "${rdmnt}" ] || [ ! -d "${rdmnt}" ]; then
   echo "FATAL: Invalid ramdisk root '${rdmnt}'"
   echo "Usage: $0 <rdmnt>"
   exit 1
+fi
+
+if [ -z "${ROOT}" ]; then
+	echo "FATAL: ROOT not specified"
+	exit 1
+fi
+
+if [[ ! -x ${SVCCFG} ]]; then
+	echo "FATAL: Missing svccfg-native binary from illumos build looked in '${SVCCFG}'"
+	exit 1
 fi
 
 # TODO check that we're root
@@ -40,7 +33,6 @@ export SVCCFG_DTD=${rdmnt}/usr/share/lib/xml/dtd/service_bundle.dtd.1
 export SVCCFG_REPOSITORY=${REPO_DB}
 export SVCCFG_CONFIGD_PATH=/lib/svc/bin/svc.configd
 
-SVCCFG="/usr/sbin/svccfg"
 ${SVCCFG} -v repository ${REPO_DB}
 ${SVCCFG} -v add smf/manifest
 ${SVCCFG} -v import ${rdmnt}/lib/svc/manifest
@@ -51,5 +43,8 @@ ${SVCCFG} -s "system/coreadm:default" setprop config_params/global_pattern='/zon
 # ${SVCCFG} -s "system/manifest-import" setprop start/exec=:true
 ${SVCCFG} -v apply ${rdmnt}/etc/svc/profile/generic.xml
 ${SVCCFG} -v apply ${rdmnt}/etc/svc/profile/platform.xml
+
+# rcap imports with enabled=false, but applying generic.xml enables it.
+${SVCCFG} -s "rcap:default" setprop general/enabled=false
 
 exit 0
