OS-4579 No buildstamp left behind Reviewed by: Joshua M. Clulow <jmc@joyent.com>

diff --git a/tools/build_illumos b/tools/build_illumos
--- a/tools/build_illumos
+++ b/tools/build_illumos
@@ -23,9 +23,15 @@ export PATH=/opt/onbld/bin:/sbin:/usr/sbin:/usr/bin:/usr/ccs/bin:/opt/SUNWspro/b
 mkdir -p ${ROOT}/proto
 if [[ ! -f ${ROOT}/proto/buildstamp ]]; then
     if [[ -z $BUILDSTAMP ]]; then
-        BUILDSTAMP=`TZ=UTC date "+%Y%m%dT%H%M%SZ"`; export BUILDSTAMP
+        BUILDSTAMP=$(TZ=UTC date "+%Y%m%dT%H%M%SZ"); export BUILDSTAMP
     fi
-    echo ${BUILDSTAMP} > ${ROOT}/proto/buildstamp
+    echo "${BUILDSTAMP}" > ${ROOT}/proto/buildstamp
+else
+    BUILDSTAMP=$(<${ROOT}/proto/buildstamp)
+    if [[ $? -ne 0 || -z "${BUILDSTAMP}" ]]; then
+        printf "failed to read existing buildstamp\n" >&2
+        exit 1
+    fi
 fi
 
 echo "==> Building Illumos (${BUILDSTAMP})"
