Skip update and built correct iso
While on the dev-overlay branch, the standard gmake update ins't quite
the best procedure. For now, updating illumos is going to be a manual
activity. In addition, becuase it's a branch, we know that we can
actually go ahead and use ttya...

diff --git a/tools/update_base b/tools/update_base
--- a/tools/update_base
+++ b/tools/update_base
@@ -76,11 +76,11 @@ else
 	echo "illumos-extra tarball in use. Update illumos-extra manually."
 fi
 
-echo "Updating illumos-joyent... \c "
-cd $upd_root/projects/illumos
-[[ $? -eq 0 ]] || fail "can't find illumos directory"
-git_update || rm -f $upd_illumos_stamp
-echo "done"
+#echo "Updating illumos-joyent... \c "
+#cd $upd_root/projects/illumos
+#[[ $? -eq 0 ]] || fail "can't find illumos directory"
+#git_update || rm -f $upd_illumos_stamp
+#echo "done"
 
 
 echo "Updating illumos-live... \c "
