Modified to include network information and also work with tools on the live image (eg. no gsed).

diff --git a/src/sysinfo b/src/sysinfo
--- a/src/sysinfo
+++ b/src/sysinfo
@@ -4,6 +4,29 @@
 #
 # Output some JSON info representing the system.
 #
+# Important: Don't use anything here that you don't include in the live image!
+#
+
+# helper to set global "normalized" to the expanded version of MAC ($1)
+function normalize_mac()
+{
+    mac=$1
+    if [ -z "${mac}" ]; then
+      echo "FATAL: unable to normalize empty mac!"
+      exit 1
+    fi
+
+    normalized=`echo ${mac} | awk -F':' '{ print $1, $2, $3, $4, $5, $6 }' | { read o1 o2 o3 o4 o5 o6 junk
+        printf "%02x:%02x:%02x:%02x:%02x:%02x" 0x${o1} 0x${o2} 0x${o3} 0x${o4} 0x${o5} 0x${o6}
+    }`
+
+    # ensure results are 'normal'
+    echo "${normalized}" | grep "[a-fA-F0-9]\{2\}\:[a-fA-F0-9]\{2\}\:[a-fA-F0-9]\{2\}\:[a-fA-F0-9]\{2\}\:[a-fA-F0-9]\{2\}\:[a-fA-F0-9]\{2\}" >/dev/null 2>&1
+    if [ "$?" != "0" ]; then
+      echo "FATAL: failed to normalize MAC '${mac}'"
+      exit 1
+    fi
+}
 
 # Get (misnamed in prtconf) memory size in Mebibytes
 MEMORY_IN_MiB=`prtconf \
@@ -11,7 +34,7 @@ MEMORY_IN_MiB=`prtconf \
   | cut -d' ' -f3`
 
 SYSTEM_DATA=`smbios -t SMB_TYPE_SYSTEM \
-  | ggrep "Manufacturer: \|Product: \|Serial Number: \|UUID: " \
+  | egrep "Manufacturer: |Product: |Serial Number: |UUID: " \
   | sed -e 's/^ */  "/' \
   | sed -e 's/: /": "/' \
   | sed -e 's/ *$/",/'`
@@ -35,15 +58,36 @@ CPU_CORES=`psrinfo \
 
 # Populate disk list with "Size in GB" member for each disk
 DISKS=""
-for line in `disklist -s`; do
+for line in `/usr/bin/disklist -s 2>/dev/null`; do
   DISKS=`echo ${line} | tr '=' ' ' | { read device size junk
     gb_size=$((${size} / 1000000000))
-    printf "    \"${device}\": {\"Size in GB\": ${gb_size}},\n${DISKS}" \
-      | gsed -e '$s/,$//'
+    echo "\"${device}\": {\"Size in GB\": ${gb_size}}, ${DISKS}"
   }`
 done
+# clean up formatting of JSON
+DISKS=`echo ${DISKS} | sed -e "s/,$//" | sed -e 's/, /,\\
+/g' | sed -e "s/^/    /" | sed -e "s/\",\"/\", \"/"`
 
-# Out put the JSON!
+# Populate the nic list with MAC + admin=true if NIC is admin_nic,
+# ignore 'LINK SLOT ADDRESS INUSE CLIENT' line
+NICS=""
+admin_nic=`/usr/bin/bootparams 2>/dev/null | grep "admin_nic" | cut -d '=' -f2-`
+for line in `pfexec /sbin/dladm show-phys -m | grep -v "^LINK " | awk '{ print $1,$3 }' | tr ' ' '='`; do
+  NICS=`echo $line | tr '=' ' ' | { read nic mac junk
+    admin=""
+    normalize_mac ${mac}
+    mac=${normalized}
+    if [ -n "${admin_nic}" ] && [ "${admin_nic}" == "${mac}" ]; then
+      admin=",\"Admin NIC\": \"true\""
+    fi
+    echo "\"${nic}\": {\"MAC Address\": \"${mac}\"${admin}}, ${NICS}"
+  }`
+done
+# clean up formatting of JSON
+NICS=`echo ${NICS} | sed -e "s/,$//" | sed -e 's/, /,\\
+/g' | sed -e "s/^/    /" | sed -e "s/\",\"/\", \"/"`
+
+# Output the JSON!
 cat <<EOF
 {
 ${SYSTEM_DATA}
@@ -53,6 +97,9 @@ ${SYSTEM_DATA}
   "MiB of Memory": ${MEMORY_IN_MiB},
   "Disks": {
 ${DISKS}
+  },
+  "Network Interfaces": {
+${NICS}
   }
 }
 EOF
